In [1]:
#Question No.2 [Data:- Random Forest with target variable Taxable_income]
import pandas as pd

In [2]:
#Read the file
fraudcheck= pd.read_csv('Fraud_check.csv') 
fraudcheck

,Undergrad,Marital.Status,Taxable.Income,City.Population,Work.Experience,Urban
0,NO,Single,68833,50047,10,YES
1,YES,Divorced,33700,134075,18,YES
2,NO,Married,36925,160205,30,YES
3,YES,Single,50190,193264,15,YES
4,NO,Married,81002,27533,28,NO
...,...,...,...,...,...,...
595,YES,Divorced,76340,39492,7,YES
596,YES,Divorced,69967,55369,2,YES
597,NO,Divorced,47334,154058,0,YES
598,YES,Married,98592,180083,17,NO
599,NO,Divorced,96519,158137,16,NO

In [3]:
fraudcheck.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Undergrad        600 non-null    object
 1   Marital.Status   600 non-null    object
 2   Taxable.Income   600 non-null    int64
 3   City.Population  600 non-null    int64
 4   Work.Experience  600 non-null    int64
 5   Urban            600 non-null    object
dtypes: int64(3), object(3)
memory usage: 28.2+ KB

In [4]:
fraudcheck.describe()

       Taxable.Income  City.Population  Work.Experience
count      600.000000       600.000000       600.000000
mean     55208.375000    108747.368333        15.558333
std      26204.827597     49850.075134         8.842147
min      10003.000000     25779.000000         0.000000
25%      32871.500000     66966.750000         8.000000
50%      55074.500000    106493.500000        15.000000
75%      78611.750000    150114.250000        24.000000
max      99619.000000    199778.000000        30.000000

In [5]:
#Rename the column
fraudcheck=fraudcheck.rename({"Taxable.Income":"Taxable_income"},axis=1)
fraudcheck

,Undergrad,Marital.Status,Taxable_income,City.Population,Work.Experience,Urban
0,NO,Single,68833,50047,10,YES
1,YES,Divorced,33700,134075,18,YES
2,NO,Married,36925,160205,30,YES
3,YES,Single,50190,193264,15,YES
4,NO,Married,81002,27533,28,NO
...,...,...,...,...,...,...
595,YES,Divorced,76340,39492,7,YES
596,YES,Divorced,69967,55369,2,YES
597,NO,Divorced,47334,154058,0,YES
598,YES,Married,98592,180083,17,NO
599,NO,Divorced,96519,158137,16,NO

In [6]:
pd.set_option("display.max_rows", None) 
fraudcheck

,Undergrad,Marital.Status,Taxable_income,City.Population,Work.Experience,Urban
0,NO,Single,68833,50047,10,YES
1,YES,Divorced,33700,134075,18,YES
2,NO,Married,36925,160205,30,YES
3,YES,Single,50190,193264,15,YES
4,NO,Married,81002,27533,28,NO
5,NO,Divorced,33329,116382,0,NO
6,NO,Divorced,83357,80890,8,YES
7,YES,Single,62774,131253,3,YES
8,NO,Single,83519,102481,12,YES
9,YES,Divorced,98152,155482,4,YES
10,NO,Single,29732,102602,19,YES
11,NO,Single,61063,94875,6,YES
12,NO,Divorced,11794,148033,14,YES
13,NO,Married,61830,86649,16,YES
14,NO,Married,64070,57529,13,YES
15,NO,Divorced,69869,107764,29,NO
16,YES,Divorced,24987,34551,29,NO
17,YES,Married,39476,57194,25,NO
18,YES,Divorced,97957,59269,6,NO
19,NO,Single,10987,126953,30,YES
20,YES,Single,88636,147222,26,NO
21,YES,Divorced,14310,29106,7,YES
22,YES,Divorced,78969,155342,14,NO
23,NO,Single,92040,50495,12,YES
24,NO,Divorced,38239,28495,30,NO
25,NO,Divorced,31417,124606,27,YES
26,YES,Divorced,55299,169128,15,NO
27,YES,Single,87778,28542,12,YES
28,YES,Single,10379,128766,5,YES
29,YES,Divorced,94033,41863,30,YES
30,YES,Divorced,73854,117788,0,YES
31,NO,Divorced,64007,147414,21,NO
32,YES,Married,97200,51911,23,NO
33,YES,Single,82071,157251,21,NO
34,YES,Divorced,12514,183767,1,YES
35,YES,Married,31336,41117,30,YES
36,YES,Married,10163,193995,5,YES
37,NO,Married,68513,66912,5,YES
38,NO,Single,14912,177575,3,NO
39,NO,Married,74010,54981,16,YES
40,NO,Single,50777,199697,26,YES
41,YES,Married,49436,91524,1,NO
42,NO,Single,96485,51666,12,NO
43,YES,Divorced,70339,50020,10,NO
44,YES,Divorced,33614,98880,22,NO
45,YES,Married,81079,183095,14,YES
46,YES,Married,31532,137346,27,YES
47,YES,Single,44034,34964,2,NO
48,NO,Married,16264,35480,12,NO
49,NO,Divorced,45706,160195,15,YES
50,YES,Single,79616,145804,3,YES
51,YES,Single,40137,174042,30,NO
52,NO,Single,97703,91828,23,NO
53,YES,Single,21917,139143,7,YES
54,NO,Divorced,81939,98207,23,NO
55,YES,Single,19925,89965,16,YES
56,NO,Married,34703,69832,25,YES
57,NO,Single,78573,70744,13,NO
58,YES,Single,10870,158047,15,NO
59,NO,Single,65065,102228,11,NO
60,YES,Married,94418,91138,23,NO
61,YES,Married,26972,86169,8,NO
62,NO,Divorced,91684,147684,13,YES
63,YES,Divorced,51685,95831,9,NO
64,YES,Single,62158,118261,15,NO
65,NO,Divorced,58312,194738,29,NO
66,YES,Married,42507,66985,12,YES
67,YES,Married,61486,173986,24,NO
68,NO,Single,10150,139642,5,NO
69,YES,Single,99619,86896,29,NO
70,YES,Divorced,89302,80904,3,YES
71,NO,Single,94287,105680,22,NO
72,YES,Divorced,41344,108300,27,YES
73,YES,Single,41382,174789,2,YES
74,NO,Divorced,32434,182319,17,NO
75,NO,Married,61105,50404,19,YES
76,YES,Married,67628,129164,11,NO
77,YES,Married,31458,118344,26,NO
78,YES,Divorced,73411,143153,0,NO
79,NO,Divorced,10329,140885,7,YES
80,NO,Married,44947,28184,26,NO
81,YES,Divorced,35610,121608,24,NO
82,NO,Divorced,66564,111068,26,YES
83,NO,Divorced,87348,73963,18,YES
84,NO,Married,69098,178083,4,YES
85,YES,Divorced,28449,125155,12,YES
86,YES,Divorced,39277,97520,29,YES
87,YES,Single,13747,64075,23,NO
88,NO,Married,86652,63896,24,YES
89,YES,Married,26741,176050,20,NO
90,NO,Divorced,77634,101232,29,NO
91,YES,Married,99325,73733,10,YES
92,NO,Divorced,85651,114621,13,NO
93,YES,Married,15296,137676,3,YES
94,NO,Single,10348,122705,6,YES
95,YES,Single,41395,121498,28,YES
96,NO,Single,22258,63622,17,NO
97,YES,Divorced,79583,37849,19,YES
98,YES,Married,22187,77053,18,YES
99,NO,Married,52495,114350,12,NO
100,YES,Single,93078,46444,25,NO
101,YES,Married,35072,50490,20,YES
102,YES,Divorced,32662,91488,23,NO
103,NO,Divorced,89250,76318,5,YES
104,NO,Single,41641,174423,14,NO
105,NO,Single,55873,46893,15,NO
106,YES,Single,19169,58535,20,YES
107,NO,Married,46629,52424,6,YES
108,YES,Married,51927,120894,10,YES
109,YES,Married,69224,178585,8,YES
110,NO,Single,24557,32450,19,YES
111,NO,Single,77762,164526,11,YES
112,YES,Single,96355,193038,26,YES
113,YES,Married,90910,100347,7,YES
114,NO,Single,21945,197934,7,NO
115,YES,Divorced,79357,78251,21,YES
116,NO,Married,42784,132570,12,NO
117,NO,Single,54638,96370,29,YES
118,NO,Divorced,29944,199174,10,NO
119,NO,Divorced,97318,47202,30,YES
120,YES,Single,52022,135886,11,YES
121,YES,Married,20391,86648,16,YES
122,YES,Married,21016,140762,26,NO
123,YES,Married,26679,79683,26,NO
124,YES,Divorced,70682,139324,13,NO
125,YES,Divorced,87326,155669,11,NO
126,YES,Divorced,15853,195022,3,YES
127,NO,Single,75501,93035,28,YES
128,NO,Married,97984,100897,27,YES
129,YES,Single,53378,65469,26,NO
130,YES,Single,93458,87730,7,YES
131,YES,Single,56501,174321,16,YES
132,NO,Divorced,46955,67820,12,NO
133,NO,Single,33492,86646,14,YES
134,YES,Married,35832,190365,28,NO
135,YES,Divorced,12470,75323,19,YES
136,NO,Divorced,53981,53513,9,NO
137,YES,Single,22773,115884,6,NO
138,NO,Single,84691,155335,25,NO
139,YES,Divorced,50087,86904,20,NO
140,YES,Married,27877,93390,4,YES
141,YES,Married,56647,194364,23,YES
142,NO,Single,59419,122654,26,YES
143,YES,Single,26783,154013,11,NO
144,YES,Single,79453,156503,29,YES
145,NO,Divorced,33962,197422,2,YES
146,NO,Divorced,84429,57931,28,YES
147,YES,Divorced,63057,163252,28,NO
148,NO,Married,43128,197038,21,NO
149,NO,Single,40220,49505,25,NO
150,NO,Married,79700,161759,28,NO
151,NO,Single,67083,109110,10,NO
152,NO,Single,22054,91889,16,NO
153,YES,Divorced,18192,114841,28,NO
154,NO,Single,25222,82520,29,YES
155,YES,Single,58635,139624,7,NO
156,YES,Married,39114,125987,3,YES
157,YES,Married,48738,115631,5,NO
158,NO,Divorced,28496,163347,11,NO
159,YES,Single,62209,28504,1,NO
160,YES,Divorced,87677,79972,0,YES
161,YES,Married,93659,185596,30,YES
162,YES,Married,56503,177468,21,YES
163,YES,Divorced,27081,91851,15,YES
164,YES,Single,48779,153192,28,NO
165,YES,Married,91304,38463,23,YES
166,NO,Married,49520,73466,22,YES
167,NO,Married,41117,194381,25,NO
168,NO,Divorced,18199,167629,30,NO
169,YES,Single,76992,76933,6,YES
170,NO,Divorced,98588,143402,10,NO
171,YES,Married,20719,103614,24,NO
172,NO,Married,13068,52819,23,YES
173,YES,Single,84835,105110,16,YES
174,YES,Single,44795,149857,8,NO
175,YES,Single,39052,57055,13,NO
176,NO,Married,38704,75169,28,NO
177,NO,Married,98416,31156,13,YES
178,NO,Single,86958,85832,15,YES
179,YES,Married,29222,192451,22,YES
180,YES,Single,71357,149101,19,NO
181,NO,Divorced,29543,36116,20,NO
182,NO,Divorced,23855,89632,4,YES
183,NO,Single,84836,39523,30,YES
184,NO,Divorced,93307,70138,15,YES
185,NO,Married,64614,92975,0,YES
186,NO,Married,72949,166976,19,YES
187,NO,Single,79211,59558,5,YES
188,NO,Divorced,28707,137569,10,NO
189,YES,Married,83229,189301,11,YES
190,NO,Single,73620,90459,19,NO
191,NO,Single,70819,176341,7,YES
192,YES,Married,48313,126556,10,YES
193,YES,Married,37481,198213,25,NO
194,YES,Single,20851,103981,28,NO
195,YES,Single,86079,181370,13,YES
196,YES,Married,10933,28410,21,NO
197,NO,Single,66905,98056,4,YES
198,NO,Single,36890,48025,28,YES
199,YES,Married,19060,145744,9,YES
200,YES,Single,61906,162777,17,YES
201,YES,Divorced,31088,58225,27,YES
202,YES,Single,70365,28661,0,YES
203,YES,Divorced,56536,117260,4,NO
204,NO,Married,16992,173091,14,NO
205,NO,Married,14300,131906,20,YES
206,YES,Single,51914,52227,16,YES
207,YES,Married,12083,138108,28,NO
208,YES,Single,71376,141502,3,NO
209,YES,Single,99307,186239,25,YES
210,YES,Single,35200,125993,13,YES
211,YES,Married,70812,57194,8,YES
212,YES,Divorced,62067,112659,14,NO
213,YES,Single,62365,107069,13,NO
214,NO,Divorced,80618,140159,16,NO
215,NO,Divorced,52891,28576,22,NO
216,NO,Divorced,31409,85128,22,NO
217,YES,Divorced,81790,179220,19,YES
218,NO,Married,57794,38091,19,NO
219,YES,Divorced,20604,26814,9,NO
220,YES,Divorced,83459,115168,30,NO
221,YES,Single,43051,134135,14,NO
222,YES,Divorced,68911,168248,27,NO
223,YES,Married,38374,192297,17,YES
224,NO,Married,86784,55717,25,YES
225,YES,Single,42488,125883,0,YES
226,NO,Single,35922,77719,28,NO
227,YES,Single,46610,182921,17,YES
228,NO,Married,28764,100696,9,YES
229,NO,Married,75170,35780,10,NO
230,NO,Married,24370,81593,14,YES
231,YES,Single,84083,153147,2,NO
232,YES,Married,11784,150349,2,NO
233,NO,Married,10003,63701,19,YES
234,NO,Single,98970,102498,14,NO
235,NO,Divorced,77735,87541,9,NO
236,YES,Married,46070,193193,3,NO
237,NO,Married,27143,128996,3,YES
238,YES,Single,56974,72968,9,YES
239,NO,Divorced,99109,76145,26,NO
240,NO,Single,32603,139146,30,YES
241,YES,Single,24215,31377,18,YES
242,NO,Divorced,33092,84368,2,YES
243,NO,Divorced,71297,181549,10,YES
244,YES,Single,68268,154647,27,NO
245,NO,Single,33810,183221,24,NO
246,YES,Single,49995,38139,25,NO
247,YES,Divorced,11865,108245,1,NO
248,NO,Single,28904,105374,17,YES
249,YES,Single,39144,35376,0,YES
250,NO,Married,31591,156973,16,NO
251,YES,Single,30167,173228,7,NO
252,NO,Single,72382,40855,28,YES
253,YES,Single,79869,77256,29,NO
254,NO,Divorced,70526,193263,26,NO
255,YES,Married,38143,170030,8,NO
256,YES,Married,70298,168568,14,NO
257,YES,Married,54747,31611,17,YES
258,NO,Divorced,92997,74119,28,YES
259,NO,Married,24347,197841,7,NO
260,YES,Single,57445,92333,28,NO
261,NO,Single,70645,68788,7,YES
262,NO,Divorced,69540,120415,21,NO
263,YES,Married,70712,69386,21,YES
264,NO,Single,32900,118899,5,NO
265,NO,Married,14326,101996,4,YES
266,YES,Married,43865,173276,17,YES
267,NO,Single,29046,183946,11,NO
268,NO,Single,95088,98378,3,YES
269,YES,Married,38586,125450,13,YES
270,NO,Married,30468,130680,5,NO
271,NO,Single,42254,183682,20,NO
272,NO,Single,32467,126488,1,YES
273,YES,Divorced,68404,58942,20,NO
274,YES,Married,58451,112584,25,NO
275,YES,Married,86208,55591,0,YES
276,NO,Single,62426,44251,17,YES
277,NO,Divorced,63710,117364,11,NO
278,NO,Married,25062,114823,11,NO
279,YES,Single,56438,74136,12,YES
280,NO,Divorced,17783,33184,1,NO
281,NO,Single,92426,167403,7,YES
282,YES,Married,64667,59590,29,NO
283,YES,Divorced,32483,129276,22,NO
284,NO,Divorced,15673,188383,22,YES
285,NO,Single,77511,63420,10,NO
286,YES,Divorced,76182,113724,6,NO
287,YES,Single,89831,77102,1,YES
288,YES,Married,12072,174196,21,YES
289,NO,Single,81231,196816,14,NO
290,YES,Married,48169,193003,30,YES
291,YES,Single,31699,62475,26,YES
292,YES,Single,15710,76406,1,YES
293,NO,Divorced,31645,43899,21,YES
294,YES,Single,98933,74074,2,NO
295,YES,Married,52912,40089,10,NO
296,YES,Divorced,68756,167600,26,NO
297,NO,Married,41087,36924,15,NO
298,NO,Single,46798,119904,21,YES
299,YES,Single,34475,197916,7,NO
300,NO,Married,98334,74052,30,NO
301,YES,Married,10900,39797,11,NO
302,YES,Divorced,61445,97109,27,NO
303,YES,Divorced,78796,189061,13,YES
304,YES,Divorced,62141,106757,23,YES
305,NO,Single,90945,161265,29,YES
306,YES,Divorced,88918,185099,12,NO
307,NO,Divorced,62873,31819,25,NO
308,YES,Married,70949,183445,30,NO
309,YES,Single,31521,123761,20,YES
310,YES,Divorced,59615,189435,22,YES
311,NO,Married,52111,50013,19,NO
312,YES,Single,34598,31641,18,NO
313,YES,Single,61124,124848,2,NO
314,NO,Single,59689,85255,4,NO
315,YES,Divorced,23075,176278,19,NO
316,NO,Married,48192,70323,25,NO
317,YES,Married,77367,116745,23,NO
318,NO,Divorced,82625,121324,14,YES
319,YES,Divorced,51802,153308,24,YES
320,YES,Single,78922,78897,11,YES
321,NO,Single,38670,84215,6,YES
322,NO,Divorced,48392,160932,24,YES
323,YES,Married,47425,165175,13,NO
324,YES,Single,73906,171288,15,NO
325,NO,Single,94013,25779,16,YES
326,YES,Divorced,27698,165001,19,YES
327,YES,Married,26793,162777,7,NO
328,NO,Divorced,67033,93414,12,YES
329,NO,Single,20109,39360,10,NO
330,NO,Married,95185,43176,29,NO
331,YES,Married,27684,60999,15,YES
332,YES,Divorced,98240,84132,1,NO
333,YES,Single,18032,44775,13,YES
334,NO,Single,46470,118274,13,YES
335,YES,Married,33301,140998,15,NO
336,NO,Married,62800,73146,5,NO
337,YES,Married,27520,73490,7,NO
338,YES,Divorced,26094,111264,23,NO
339,YES,Single,13571,110940,10,NO
340,YES,Married,36239,54437,21,YES
341,NO,Married,77082,83900,8,YES
342,YES,Married,71572,31097,7,YES
343,YES,Divorced,30495,161143,17,NO
344,NO,Married,49771,192313,5,YES
345,YES,Divorced,32905,118798,6,NO
346,NO,Single,21337,134635,30,YES
347,NO,Married,16082,80991,0,YES
348,YES,Single,43883,42269,2,NO
349,YES,Divorced,15491,72255,30,YES
350,NO,Married,48081,89949,25,NO
351,YES,Married,36317,114922,12,NO
352,NO,Divorced,15627,72115,16,YES
353,YES,Married,51028,141622,29,NO
354,YES,Married,14422,176891,27,YES
355,YES,Single,45525,56488,17,NO
356,NO,Married,23480,46480,27,NO
357,NO,Married,19184,84034,28,NO
358,YES,Single,80239,96432,24,YES
359,YES,Single,33215,157299,11,NO
360,YES,Single,65203,107937,5,YES
361,YES,Divorced,65190,62671,20,NO
362,YES,Divorced,16320,75552,17,YES
363,YES,Single,21696,52584,7,YES
364,YES,Married,56129,62943,17,NO
365,NO,Divorced,74971,134321,10,YES
366,YES,Married,33356,131469,30,NO
367,YES,Married,29607,95404,24,YES
368,YES,Divorced,95319,128428,14,NO
369,NO,Married,94413,89122,28,NO
370,NO,Divorced,78963,86119,5,YES
371,YES,Single,66865,75580,5,NO
372,YES,Married,40427,168473,9,NO
373,NO,Married,93733,175719,21,YES
374,YES,Divorced,63543,147614,9,YES
375,NO,Married,41184,130935,2,NO
376,NO,Divorced,96652,188067,26,NO
377,YES,Single,56555,103490,30,NO
378,YES,Divorced,36457,152471,6,NO
379,NO,Single,26101,112774,13,NO
380,YES,Married,36156,197699,2,NO
381,NO,Single,49958,61920,4,NO
382,YES,Divorced,68696,139269,29,NO
383,YES,Married,97453,148246,5,YES
384,YES,Married,68533,147346,25,NO
385,NO,Single,96438,140132,27,NO
386,NO,Single,50348,140642,27,YES
387,YES,Single,85016,56597,9,YES
388,YES,Divorced,73188,151636,4,YES
389,YES,Single,64225,183187,5,YES
390,YES,Single,64437,57324,17,NO
391,NO,Married,66330,29934,1,NO
392,YES,Divorced,26372,37776,15,NO
393,NO,Married,30714,68687,30,YES
394,NO,Divorced,84263,64990,21,YES
395,YES,Single,86531,183094,5,NO
396,YES,Single,93090,176330,21,NO
397,NO,Married,79373,91689,14,YES
398,NO,Married,17440,64070,2,YES
399,NO,Single,81536,74497,21,NO
400,YES,Married,62494,197421,16,NO
401,NO,Married,37580,73065,20,NO
402,YES,Divorced,60822,105376,11,NO
403,NO,Divorced,96032,130912,27,YES
404,YES,Divorced,91545,34334,21,YES
405,NO,Divorced,73313,140266,28,NO
406,NO,Married,54345,107688,2,NO
407,NO,Single,33138,52144,6,NO
408,YES,Divorced,33579,77059,22,NO
409,NO,Single,83094,163058,1,NO
410,NO,Divorced,90065,41152,27,NO
411,NO,Married,51913,46253,19,NO
412,YES,Single,81378,28446,11,NO
413,YES,Single,32236,112890,11,YES
414,NO,Divorced,97980,27300,1,YES
415,NO,Divorced,38626,131493,21,NO
416,NO,Single,64230,33982,30,NO
417,NO,Divorced,38183,76625,2,NO
418,YES,Divorced,89277,104183,18,NO
419,NO,Married,68269,138074,20,NO
420,NO,Divorced,58751,84473,2,NO
421,YES,Single,88720,135185,13,NO
422,NO,Divorced,99311,191983,14,YES
423,NO,Married,94528,80249,19,YES
424,YES,Married,72268,94199,0,YES
425,YES,Divorced,79593,121506,27,NO
426,YES,Divorced,94247,50373,25,YES
427,NO,Divorced,76700,99025,10,NO
428,YES,Married,12011,128266,24,YES
429,NO,Single,87935,153748,30,YES
430,YES,Married,98720,161215,8,NO
431,NO,Single,38638,168360,25,YES
432,NO,Married,37857,157217,11,YES
433,NO,Married,15532,129265,14,YES
434,YES,Single,22159,87188,19,YES
435,NO,Divorced,91547,111774,4,YES
436,NO,Divorced,98738,158057,4,YES
437,YES,Married,21966,117250,20,YES
438,NO,Single,14398,74697,14,NO
439,YES,Divorced,18572,48956,8,NO
440,NO,Single,77312,170407,13,YES
441,NO,Divorced,42074,70314,24,NO
442,YES,Single,82799,193775,27,NO
443,YES,Single,12659,189209,9,NO
444,YES,Single,19649,36956,14,NO
445,NO,Divorced,50119,128451,12,NO
446,NO,Single,18888,65708,28,NO
447,NO,Married,83061,166606,5,YES
448,YES,Single,39343,114597,28,YES
449,NO,Married,92007,27875,11,NO
450,YES,Divorced,78728,91936,8,YES
451,YES,Divorced,48640,108262,10,YES
452,NO,Single,92070,42620,10,NO
453,YES,Single,97341,41504,26,NO
454,NO,Married,97493,29602,15,YES
455,NO,Married,78400,65533,23,YES
456,NO,Single,52862,53788,23,YES
457,NO,Married,11804,36055,24,YES
458,YES,Single,10455,110892,18,YES
459,YES,Divorced,25766,125407,21,NO
460,NO,Divorced,58199,54701,10,YES
461,NO,Single,88613,163901,6,YES
462,NO,Divorced,16690,149327,17,NO
463,NO,Divorced,71164,40460,3,YES
464,NO,Married,48825,143349,16,YES
465,NO,Divorced,29236,116282,21,NO
466,NO,Married,59689,186013,16,NO
467,YES,Divorced,48940,106946,20,YES
468,YES,Divorced,64320,38814,18,YES
469,YES,Single,84845,65487,13,YES
470,YES,Married,52663,148686,26,NO
471,NO,Single,17957,192410,21,YES
472,NO,Married,69018,151963,11,YES
473,YES,Single,58496,147367,16,YES
474,YES,Divorced,99128,80729,0,NO
475,NO,Single,35868,36081,12,YES
476,NO,Single,79478,183057,7,YES
477,YES,Divorced,57402,158849,29,NO
478,NO,Divorced,73795,65242,6,NO
479,YES,Married,58403,68995,21,NO
480,NO,Divorced,85972,72252,26,YES
481,YES,Single,62998,120012,13,NO
482,NO,Single,32786,125771,12,NO
483,NO,Single,17962,100961,10,NO
484,YES,Married,59440,114646,28,YES
485,NO,Single,94772,52766,23,NO
486,YES,Single,80083,57230,29,YES
487,YES,Single,81026,83402,13,YES
488,YES,Single,86883,76718,10,YES
489,YES,Married,39444,148821,6,NO
490,NO,Married,35886,120996,24,NO
491,NO,Divorced,24541,82029,10,NO
492,YES,Single,54502,98123,18,YES
493,NO,Married,17183,103226,29,NO
494,NO,Single,39562,197045,13,YES
495,NO,Married,70157,59156,24,NO
496,YES,Divorced,72151,59382,5,YES
497,NO,Single,65170,100331,3,NO
498,YES,Single,67936,164924,24,YES
499,YES,Single,93339,48744,2,YES
500,YES,Single,57365,158780,11,YES
501,NO,Divorced,56628,55842,4,YES
502,NO,Married,83814,53240,1,YES
503,YES,Married,75324,81550,17,YES
504,NO,Divorced,46939,198571,19,YES
505,NO,Divorced,71428,74910,15,YES
506,NO,Single,23884,111105,8,YES
507,YES,Single,95145,101272,24,YES
508,NO,Single,46002,195357,19,NO
509,NO,Married,20309,65531,27,YES
510,YES,Married,72115,75436,14,YES
511,NO,Married,42769,153233,5,YES
512,YES,Single,91870,137948,22,YES
513,NO,Divorced,55308,140400,10,NO
514,NO,Divorced,60789,31380,6,NO
515,NO,Divorced,51363,87868,13,NO
516,YES,Single,99239,76337,18,YES
517,NO,Single,19272,195078,26,NO
518,YES,Single,44411,112591,26,YES
519,YES,Single,60915,162102,25,YES
520,NO,Divorced,98433,142426,8,YES
521,NO,Divorced,81867,51104,15,NO
522,NO,Divorced,43980,103343,10,NO
523,NO,Divorced,50286,42198,12,NO
524,YES,Married,29385,164391,27,NO
525,YES,Single,47565,75307,23,NO
526,NO,Divorced,26494,82565,12,NO
527,NO,Married,59243,180274,27,NO
528,NO,Married,91488,172612,10,NO
529,NO,Divorced,33116,83388,14,NO
530,YES,Divorced,93364,194421,17,YES
531,YES,Married,70743,124440,14,YES
532,YES,Divorced,34007,98662,16,NO
533,NO,Divorced,26128,54113,19,YES
534,YES,Married,33748,91567,13,YES
535,NO,Married,38896,189851,3,NO
536,NO,Single,40674,157025,14,NO
537,YES,Single,97111,100651,6,NO
538,NO,Married,54850,119976,12,NO
539,YES,Divorced,32948,57390,8,NO
540,YES,Single,12682,110308,22,NO
541,YES,Divorced,12453,191874,30,YES
542,YES,Married,34655,199778,27,NO
543,NO,Single,59351,130816,13,NO
544,NO,Single,29916,133877,21,YES
545,YES,Divorced,36532,109079,8,NO
546,NO,Married,94583,59091,6,NO
547,YES,Single,92819,42690,25,YES
548,YES,Divorced,76535,154393,9,YES
549,NO,Married,91220,74058,11,YES
550,NO,Married,71238,68160,2,YES
551,YES,Married,32356,123082,0,YES
552,NO,Single,89094,109191,5,YES
553,NO,Single,91462,26884,13,YES
554,NO,Divorced,75585,147788,27,NO
555,NO,Single,31629,53848,10,NO
556,NO,Single,42063,34242,12,NO
557,YES,Married,12810,157421,10,NO
558,NO,Divorced,85570,191139,12,YES
559,YES,Divorced,72026,180424,26,NO
560,NO,Divorced,90444,182562,24,NO
561,NO,Married,50403,36861,29,YES
562,YES,Divorced,78867,100064,12,NO
563,YES,Married,95920,116495,6,YES
564,YES,Married,41545,30098,11,YES
565,NO,Divorced,63912,31064,28,NO
566,NO,Married,92498,33460,28,NO
567,YES,Single,16316,129912,30,NO
568,NO,Single,68617,150036,22,YES
569,YES,Single,59860,38074,12,YES
570,NO,Single,55981,161629,29,YES
571,NO,Single,34833,95421,7,YES
572,YES,Married,39818,148068,13,NO
573,YES,Married,59227,116161,20,NO
574,YES,Divorced,44809,28768,29,YES
575,NO,Divorced,10735,95975,13,YES
576,YES,Married,50242,79653,15,YES
577,YES,Married,56166,52940,5,YES
578,NO,Divorced,42483,185339,6,NO
579,YES,Single,70572,125112,7,YES
580,YES,Divorced,31721,123335,1,YES
581,YES,Divorced,31085,57473,10,YES
582,YES,Married,84931,32907,12,YES
583,NO,Married,69036,28874,19,NO
584,NO,Divorced,42679,155684,4,YES

In [7]:
#Convert data type from continuous into categorical data type by using some condition & applying (cut) function & creating new column[Taxable_income1]
#Taxable_income<30000 = Risky
#Taxable_income>30000 = Good
category=pd.cut(fraudcheck.Taxable_income,bins=[10003,30000,99619],labels=['Risky','Good'])
fraudcheck.insert(6,'Taxable_income1',category) 
fraudcheck

,Undergrad,Marital.Status,Taxable_income,City.Population,Work.Experience,Urban,Taxable_income1
0,NO,Single,68833,50047,10,YES,Good
1,YES,Divorced,33700,134075,18,YES,Good
2,NO,Married,36925,160205,30,YES,Good
3,YES,Single,50190,193264,15,YES,Good
4,NO,Married,81002,27533,28,NO,Good
5,NO,Divorced,33329,116382,0,NO,Good
6,NO,Divorced,83357,80890,8,YES,Good
7,YES,Single,62774,131253,3,YES,Good
8,NO,Single,83519,102481,12,YES,Good
9,YES,Divorced,98152,155482,4,YES,Good
10,NO,Single,29732,102602,19,YES,Risky
11,NO,Single,61063,94875,6,YES,Good
12,NO,Divorced,11794,148033,14,YES,Risky
13,NO,Married,61830,86649,16,YES,Good
14,NO,Married,64070,57529,13,YES,Good
15,NO,Divorced,69869,107764,29,NO,Good
16,YES,Divorced,24987,34551,29,NO,Risky
17,YES,Married,39476,57194,25,NO,Good
18,YES,Divorced,97957,59269,6,NO,Good
19,NO,Single,10987,126953,30,YES,Risky
20,YES,Single,88636,147222,26,NO,Good
21,YES,Divorced,14310,29106,7,YES,Risky
22,YES,Divorced,78969,155342,14,NO,Good
23,NO,Single,92040,50495,12,YES,Good
24,NO,Divorced,38239,28495,30,NO,Good
25,NO,Divorced,31417,124606,27,YES,Good
26,YES,Divorced,55299,169128,15,NO,Good
27,YES,Single,87778,28542,12,YES,Good
28,YES,Single,10379,128766,5,YES,Risky
29,YES,Divorced,94033,41863,30,YES,Good
30,YES,Divorced,73854,117788,0,YES,Good
31,NO,Divorced,64007,147414,21,NO,Good
32,YES,Married,97200,51911,23,NO,Good
33,YES,Single,82071,157251,21,NO,Good
34,YES,Divorced,12514,183767,1,YES,Risky
35,YES,Married,31336,41117,30,YES,Good
36,YES,Married,10163,193995,5,YES,Risky
37,NO,Married,68513,66912,5,YES,Good
38,NO,Single,14912,177575,3,NO,Risky
39,NO,Married,74010,54981,16,YES,Good
40,NO,Single,50777,199697,26,YES,Good
41,YES,Married,49436,91524,1,NO,Good
42,NO,Single,96485,51666,12,NO,Good
43,YES,Divorced,70339,50020,10,NO,Good
44,YES,Divorced,33614,98880,22,NO,Good
45,YES,Married,81079,183095,14,YES,Good
46,YES,Married,31532,137346,27,YES,Good
47,YES,Single,44034,34964,2,NO,Good
48,NO,Married,16264,35480,12,NO,Risky
49,NO,Divorced,45706,160195,15,YES,Good
50,YES,Single,79616,145804,3,YES,Good
51,YES,Single,40137,174042,30,NO,Good
52,NO,Single,97703,91828,23,NO,Good
53,YES,Single,21917,139143,7,YES,Risky
54,NO,Divorced,81939,98207,23,NO,Good
55,YES,Single,19925,89965,16,YES,Risky
56,NO,Married,34703,69832,25,YES,Good
57,NO,Single,78573,70744,13,NO,Good
58,YES,Single,10870,158047,15,NO,Risky
59,NO,Single,65065,102228,11,NO,Good
60,YES,Married,94418,91138,23,NO,Good
61,YES,Married,26972,86169,8,NO,Risky
62,NO,Divorced,91684,147684,13,YES,Good
63,YES,Divorced,51685,95831,9,NO,Good
64,YES,Single,62158,118261,15,NO,Good
65,NO,Divorced,58312,194738,29,NO,Good
66,YES,Married,42507,66985,12,YES,Good
67,YES,Married,61486,173986,24,NO,Good
68,NO,Single,10150,139642,5,NO,Risky
69,YES,Single,99619,86896,29,NO,Good
70,YES,Divorced,89302,80904,3,YES,Good
71,NO,Single,94287,105680,22,NO,Good
72,YES,Divorced,41344,108300,27,YES,Good
73,YES,Single,41382,174789,2,YES,Good
74,NO,Divorced,32434,182319,17,NO,Good
75,NO,Married,61105,50404,19,YES,Good
76,YES,Married,67628,129164,11,NO,Good
77,YES,Married,31458,118344,26,NO,Good
78,YES,Divorced,73411,143153,0,NO,Good
79,NO,Divorced,10329,140885,7,YES,Risky
80,NO,Married,44947,28184,26,NO,Good
81,YES,Divorced,35610,121608,24,NO,Good
82,NO,Divorced,66564,111068,26,YES,Good
83,NO,Divorced,87348,73963,18,YES,Good
84,NO,Married,69098,178083,4,YES,Good
85,YES,Divorced,28449,125155,12,YES,Risky
86,YES,Divorced,39277,97520,29,YES,Good
87,YES,Single,13747,64075,23,NO,Risky
88,NO,Married,86652,63896,24,YES,Good
89,YES,Married,26741,176050,20,NO,Risky
90,NO,Divorced,77634,101232,29,NO,Good
91,YES,Married,99325,73733,10,YES,Good
92,NO,Divorced,85651,114621,13,NO,Good
93,YES,Married,15296,137676,3,YES,Risky
94,NO,Single,10348,122705,6,YES,Risky
95,YES,Single,41395,121498,28,YES,Good
96,NO,Single,22258,63622,17,NO,Risky
97,YES,Divorced,79583,37849,19,YES,Good
98,YES,Married,22187,77053,18,YES,Risky
99,NO,Married,52495,114350,12,NO,Good
100,YES,Single,93078,46444,25,NO,Good
101,YES,Married,35072,50490,20,YES,Good
102,YES,Divorced,32662,91488,23,NO,Good
103,NO,Divorced,89250,76318,5,YES,Good
104,NO,Single,41641,174423,14,NO,Good
105,NO,Single,55873,46893,15,NO,Good
106,YES,Single,19169,58535,20,YES,Risky
107,NO,Married,46629,52424,6,YES,Good
108,YES,Married,51927,120894,10,YES,Good
109,YES,Married,69224,178585,8,YES,Good
110,NO,Single,24557,32450,19,YES,Risky
111,NO,Single,77762,164526,11,YES,Good
112,YES,Single,96355,193038,26,YES,Good
113,YES,Married,90910,100347,7,YES,Good
114,NO,Single,21945,197934,7,NO,Risky
115,YES,Divorced,79357,78251,21,YES,Good
116,NO,Married,42784,132570,12,NO,Good
117,NO,Single,54638,96370,29,YES,Good
118,NO,Divorced,29944,199174,10,NO,Risky
119,NO,Divorced,97318,47202,30,YES,Good
120,YES,Single,52022,135886,11,YES,Good
121,YES,Married,20391,86648,16,YES,Risky
122,YES,Married,21016,140762,26,NO,Risky
123,YES,Married,26679,79683,26,NO,Risky
124,YES,Divorced,70682,139324,13,NO,Good
125,YES,Divorced,87326,155669,11,NO,Good
126,YES,Divorced,15853,195022,3,YES,Risky
127,NO,Single,75501,93035,28,YES,Good
128,NO,Married,97984,100897,27,YES,Good
129,YES,Single,53378,65469,26,NO,Good
130,YES,Single,93458,87730,7,YES,Good
131,YES,Single,56501,174321,16,YES,Good
132,NO,Divorced,46955,67820,12,NO,Good
133,NO,Single,33492,86646,14,YES,Good
134,YES,Married,35832,190365,28,NO,Good
135,YES,Divorced,12470,75323,19,YES,Risky
136,NO,Divorced,53981,53513,9,NO,Good
137,YES,Single,22773,115884,6,NO,Risky
138,NO,Single,84691,155335,25,NO,Good
139,YES,Divorced,50087,86904,20,NO,Good
140,YES,Married,27877,93390,4,YES,Risky
141,YES,Married,56647,194364,23,YES,Good
142,NO,Single,59419,122654,26,YES,Good
143,YES,Single,26783,154013,11,NO,Risky
144,YES,Single,79453,156503,29,YES,Good
145,NO,Divorced,33962,197422,2,YES,Good
146,NO,Divorced,84429,57931,28,YES,Good
147,YES,Divorced,63057,163252,28,NO,Good
148,NO,Married,43128,197038,21,NO,Good
149,NO,Single,40220,49505,25,NO,Good
150,NO,Married,79700,161759,28,NO,Good
151,NO,Single,67083,109110,10,NO,Good
152,NO,Single,22054,91889,16,NO,Risky
153,YES,Divorced,18192,114841,28,NO,Risky
154,NO,Single,25222,82520,29,YES,Risky
155,YES,Single,58635,139624,7,NO,Good
156,YES,Married,39114,125987,3,YES,Good
157,YES,Married,48738,115631,5,NO,Good
158,NO,Divorced,28496,163347,11,NO,Risky
159,YES,Single,62209,28504,1,NO,Good
160,YES,Divorced,87677,79972,0,YES,Good
161,YES,Married,93659,185596,30,YES,Good
162,YES,Married,56503,177468,21,YES,Good
163,YES,Divorced,27081,91851,15,YES,Risky
164,YES,Single,48779,153192,28,NO,Good
165,YES,Married,91304,38463,23,YES,Good
166,NO,Married,49520,73466,22,YES,Good
167,NO,Married,41117,194381,25,NO,Good
168,NO,Divorced,18199,167629,30,NO,Risky
169,YES,Single,76992,76933,6,YES,Good
170,NO,Divorced,98588,143402,10,NO,Good
171,YES,Married,20719,103614,24,NO,Risky
172,NO,Married,13068,52819,23,YES,Risky
173,YES,Single,84835,105110,16,YES,Good
174,YES,Single,44795,149857,8,NO,Good
175,YES,Single,39052,57055,13,NO,Good
176,NO,Married,38704,75169,28,NO,Good
177,NO,Married,98416,31156,13,YES,Good
178,NO,Single,86958,85832,15,YES,Good
179,YES,Married,29222,192451,22,YES,Risky
180,YES,Single,71357,149101,19,NO,Good
181,NO,Divorced,29543,36116,20,NO,Risky
182,NO,Divorced,23855,89632,4,YES,Risky
183,NO,Single,84836,39523,30,YES,Good
184,NO,Divorced,93307,70138,15,YES,Good
185,NO,Married,64614,92975,0,YES,Good
186,NO,Married,72949,166976,19,YES,Good
187,NO,Single,79211,59558,5,YES,Good
188,NO,Divorced,28707,137569,10,NO,Risky
189,YES,Married,83229,189301,11,YES,Good
190,NO,Single,73620,90459,19,NO,Good
191,NO,Single,70819,176341,7,YES,Good
192,YES,Married,48313,126556,10,YES,Good
193,YES,Married,37481,198213,25,NO,Good
194,YES,Single,20851,103981,28,NO,Risky
195,YES,Single,86079,181370,13,YES,Good
196,YES,Married,10933,28410,21,NO,Risky
197,NO,Single,66905,98056,4,YES,Good
198,NO,Single,36890,48025,28,YES,Good
199,YES,Married,19060,145744,9,YES,Risky
200,YES,Single,61906,162777,17,YES,Good
201,YES,Divorced,31088,58225,27,YES,Good
202,YES,Single,70365,28661,0,YES,Good
203,YES,Divorced,56536,117260,4,NO,Good
204,NO,Married,16992,173091,14,NO,Risky
205,NO,Married,14300,131906,20,YES,Risky
206,YES,Single,51914,52227,16,YES,Good
207,YES,Married,12083,138108,28,NO,Risky
208,YES,Single,71376,141502,3,NO,Good
209,YES,Single,99307,186239,25,YES,Good
210,YES,Single,35200,125993,13,YES,Good
211,YES,Married,70812,57194,8,YES,Good
212,YES,Divorced,62067,112659,14,NO,Good
213,YES,Single,62365,107069,13,NO,Good
214,NO,Divorced,80618,140159,16,NO,Good
215,NO,Divorced,52891,28576,22,NO,Good
216,NO,Divorced,31409,85128,22,NO,Good
217,YES,Divorced,81790,179220,19,YES,Good
218,NO,Married,57794,38091,19,NO,Good
219,YES,Divorced,20604,26814,9,NO,Risky
220,YES,Divorced,83459,115168,30,NO,Good
221,YES,Single,43051,134135,14,NO,Good
222,YES,Divorced,68911,168248,27,NO,Good
223,YES,Married,38374,192297,17,YES,Good
224,NO,Married,86784,55717,25,YES,Good
225,YES,Single,42488,125883,0,YES,Good
226,NO,Single,35922,77719,28,NO,Good
227,YES,Single,46610,182921,17,YES,Good
228,NO,Married,28764,100696,9,YES,Risky
229,NO,Married,75170,35780,10,NO,Good
230,NO,Married,24370,81593,14,YES,Risky
231,YES,Single,84083,153147,2,NO,Good
232,YES,Married,11784,150349,2,NO,Risky
233,NO,Married,10003,63701,19,YES,NaN
234,NO,Single,98970,102498,14,NO,Good
235,NO,Divorced,77735,87541,9,NO,Good
236,YES,Married,46070,193193,3,NO,Good
237,NO,Married,27143,128996,3,YES,Risky
238,YES,Single,56974,72968,9,YES,Good
239,NO,Divorced,99109,76145,26,NO,Good
240,NO,Single,32603,139146,30,YES,Good
241,YES,Single,24215,31377,18,YES,Risky
242,NO,Divorced,33092,84368,2,YES,Good
243,NO,Divorced,71297,181549,10,YES,Good
244,YES,Single,68268,154647,27,NO,Good
245,NO,Single,33810,183221,24,NO,Good
246,YES,Single,49995,38139,25,NO,Good
247,YES,Divorced,11865,108245,1,NO,Risky
248,NO,Single,28904,105374,17,YES,Risky
249,YES,Single,39144,35376,0,YES,Good
250,NO,Married,31591,156973,16,NO,Good
251,YES,Single,30167,173228,7,NO,Good
252,NO,Single,72382,40855,28,YES,Good
253,YES,Single,79869,77256,29,NO,Good
254,NO,Divorced,70526,193263,26,NO,Good
255,YES,Married,38143,170030,8,NO,Good
256,YES,Married,70298,168568,14,NO,Good
257,YES,Married,54747,31611,17,YES,Good
258,NO,Divorced,92997,74119,28,YES,Good
259,NO,Married,24347,197841,7,NO,Risky
260,YES,Single,57445,92333,28,NO,Good
261,NO,Single,70645,68788,7,YES,Good
262,NO,Divorced,69540,120415,21,NO,Good
263,YES,Married,70712,69386,21,YES,Good
264,NO,Single,32900,118899,5,NO,Good
265,NO,Married,14326,101996,4,YES,Risky
266,YES,Married,43865,173276,17,YES,Good
267,NO,Single,29046,183946,11,NO,Risky
268,NO,Single,95088,98378,3,YES,Good
269,YES,Married,38586,125450,13,YES,Good
270,NO,Married,30468,130680,5,NO,Good
271,NO,Single,42254,183682,20,NO,Good
272,NO,Single,32467,126488,1,YES,Good
273,YES,Divorced,68404,58942,20,NO,Good
274,YES,Married,58451,112584,25,NO,Good
275,YES,Married,86208,55591,0,YES,Good
276,NO,Single,62426,44251,17,YES,Good
277,NO,Divorced,63710,117364,11,NO,Good
278,NO,Married,25062,114823,11,NO,Risky
279,YES,Single,56438,74136,12,YES,Good
280,NO,Divorced,17783,33184,1,NO,Risky
281,NO,Single,92426,167403,7,YES,Good
282,YES,Married,64667,59590,29,NO,Good
283,YES,Divorced,32483,129276,22,NO,Good
284,NO,Divorced,15673,188383,22,YES,Risky
285,NO,Single,77511,63420,10,NO,Good
286,YES,Divorced,76182,113724,6,NO,Good
287,YES,Single,89831,77102,1,YES,Good
288,YES,Married,12072,174196,21,YES,Risky
289,NO,Single,81231,196816,14,NO,Good
290,YES,Married,48169,193003,30,YES,Good
291,YES,Single,31699,62475,26,YES,Good
292,YES,Single,15710,76406,1,YES,Risky
293,NO,Divorced,31645,43899,21,YES,Good
294,YES,Single,98933,74074,2,NO,Good
295,YES,Married,52912,40089,10,NO,Good
296,YES,Divorced,68756,167600,26,NO,Good
297,NO,Married,41087,36924,15,NO,Good
298,NO,Single,46798,119904,21,YES,Good
299,YES,Single,34475,197916,7,NO,Good
300,NO,Married,98334,74052,30,NO,Good
301,YES,Married,10900,39797,11,NO,Risky
302,YES,Divorced,61445,97109,27,NO,Good
303,YES,Divorced,78796,189061,13,YES,Good
304,YES,Divorced,62141,106757,23,YES,Good
305,NO,Single,90945,161265,29,YES,Good
306,YES,Divorced,88918,185099,12,NO,Good
307,NO,Divorced,62873,31819,25,NO,Good
308,YES,Married,70949,183445,30,NO,Good
309,YES,Single,31521,123761,20,YES,Good
310,YES,Divorced,59615,189435,22,YES,Good
311,NO,Married,52111,50013,19,NO,Good
312,YES,Single,34598,31641,18,NO,Good
313,YES,Single,61124,124848,2,NO,Good
314,NO,Single,59689,85255,4,NO,Good
315,YES,Divorced,23075,176278,19,NO,Risky
316,NO,Married,48192,70323,25,NO,Good
317,YES,Married,77367,116745,23,NO,Good
318,NO,Divorced,82625,121324,14,YES,Good
319,YES,Divorced,51802,153308,24,YES,Good
320,YES,Single,78922,78897,11,YES,Good
321,NO,Single,38670,84215,6,YES,Good
322,NO,Divorced,48392,160932,24,YES,Good
323,YES,Married,47425,165175,13,NO,Good
324,YES,Single,73906,171288,15,NO,Good
325,NO,Single,94013,25779,16,YES,Good
326,YES,Divorced,27698,165001,19,YES,Risky
327,YES,Married,26793,162777,7,NO,Risky
328,NO,Divorced,67033,93414,12,YES,Good
329,NO,Single,20109,39360,10,NO,Risky
330,NO,Married,95185,43176,29,NO,Good
331,YES,Married,27684,60999,15,YES,Risky
332,YES,Divorced,98240,84132,1,NO,Good
333,YES,Single,18032,44775,13,YES,Risky
334,NO,Single,46470,118274,13,YES,Good
335,YES,Married,33301,140998,15,NO,Good
336,NO,Married,62800,73146,5,NO,Good
337,YES,Married,27520,73490,7,NO,Risky
338,YES,Divorced,26094,111264,23,NO,Risky
339,YES,Single,13571,110940,10,NO,Risky
340,YES,Married,36239,54437,21,YES,Good
341,NO,Married,77082,83900,8,YES,Good
342,YES,Married,71572,31097,7,YES,Good
343,YES,Divorced,30495,161143,17,NO,Good
344,NO,Married,49771,192313,5,YES,Good
345,YES,Divorced,32905,118798,6,NO,Good
346,NO,Single,21337,134635,30,YES,Risky
347,NO,Married,16082,80991,0,YES,Risky
348,YES,Single,43883,42269,2,NO,Good
349,YES,Divorced,15491,72255,30,YES,Risky
350,NO,Married,48081,89949,25,NO,Good
351,YES,Married,36317,114922,12,NO,Good
352,NO,Divorced,15627,72115,16,YES,Risky
353,YES,Married,51028,141622,29,NO,Good
354,YES,Married,14422,176891,27,YES,Risky
355,YES,Single,45525,56488,17,NO,Good
356,NO,Married,23480,46480,27,NO,Risky
357,NO,Married,19184,84034,28,NO,Risky
358,YES,Single,80239,96432,24,YES,Good
359,YES,Single,33215,157299,11,NO,Good
360,YES,Single,65203,107937,5,YES,Good
361,YES,Divorced,65190,62671,20,NO,Good
362,YES,Divorced,16320,75552,17,YES,Risky
363,YES,Single,21696,52584,7,YES,Risky
364,YES,Married,56129,62943,17,NO,Good
365,NO,Divorced,74971,134321,10,YES,Good
366,YES,Married,33356,131469,30,NO,Good
367,YES,Married,29607,95404,24,YES,Risky
368,YES,Divorced,95319,128428,14,NO,Good
369,NO,Married,94413,89122,28,NO,Good
370,NO,Divorced,78963,86119,5,YES,Good
371,YES,Single,66865,75580,5,NO,Good
372,YES,Married,40427,168473,9,NO,Good
373,NO,Married,93733,175719,21,YES,Good
374,YES,Divorced,63543,147614,9,YES,Good
375,NO,Married,41184,130935,2,NO,Good
376,NO,Divorced,96652,188067,26,NO,Good
377,YES,Single,56555,103490,30,NO,Good
378,YES,Divorced,36457,152471,6,NO,Good
379,NO,Single,26101,112774,13,NO,Risky
380,YES,Married,36156,197699,2,NO,Good
381,NO,Single,49958,61920,4,NO,Good
382,YES,Divorced,68696,139269,29,NO,Good
383,YES,Married,97453,148246,5,YES,Good
384,YES,Married,68533,147346,25,NO,Good
385,NO,Single,96438,140132,27,NO,Good
386,NO,Single,50348,140642,27,YES,Good
387,YES,Single,85016,56597,9,YES,Good
388,YES,Divorced,73188,151636,4,YES,Good
389,YES,Single,64225,183187,5,YES,Good
390,YES,Single,64437,57324,17,NO,Good
391,NO,Married,66330,29934,1,NO,Good
392,YES,Divorced,26372,37776,15,NO,Risky
393,NO,Married,30714,68687,30,YES,Good
394,NO,Divorced,84263,64990,21,YES,Good
395,YES,Single,86531,183094,5,NO,Good
396,YES,Single,93090,176330,21,NO,Good
397,NO,Married,79373,91689,14,YES,Good
398,NO,Married,17440,64070,2,YES,Risky
399,NO,Single,81536,74497,21,NO,Good
400,YES,Married,62494,197421,16,NO,Good
401,NO,Married,37580,73065,20,NO,Good
402,YES,Divorced,60822,105376,11,NO,Good
403,NO,Divorced,96032,130912,27,YES,Good
404,YES,Divorced,91545,34334,21,YES,Good
405,NO,Divorced,73313,140266,28,NO,Good
406,NO,Married,54345,107688,2,NO,Good
407,NO,Single,33138,52144,6,NO,Good
408,YES,Divorced,33579,77059,22,NO,Good
409,NO,Single,83094,163058,1,NO,Good
410,NO,Divorced,90065,41152,27,NO,Good
411,NO,Married,51913,46253,19,NO,Good
412,YES,Single,81378,28446,11,NO,Good
413,YES,Single,32236,112890,11,YES,Good
414,NO,Divorced,97980,27300,1,YES,Good
415,NO,Divorced,38626,131493,21,NO,Good
416,NO,Single,64230,33982,30,NO,Good
417,NO,Divorced,38183,76625,2,NO,Good
418,YES,Divorced,89277,104183,18,NO,Good
419,NO,Married,68269,138074,20,NO,Good
420,NO,Divorced,58751,84473,2,NO,Good
421,YES,Single,88720,135185,13,NO,Good
422,NO,Divorced,99311,191983,14,YES,Good
423,NO,Married,94528,80249,19,YES,Good
424,YES,Married,72268,94199,0,YES,Good
425,YES,Divorced,79593,121506,27,NO,Good
426,YES,Divorced,94247,50373,25,YES,Good
427,NO,Divorced,76700,99025,10,NO,Good
428,YES,Married,12011,128266,24,YES,Risky
429,NO,Single,87935,153748,30,YES,Good
430,YES,Married,98720,161215,8,NO,Good
431,NO,Single,38638,168360,25,YES,Good
432,NO,Married,37857,157217,11,YES,Good
433,NO,Married,15532,129265,14,YES,Risky
434,YES,Single,22159,87188,19,YES,Risky
435,NO,Divorced,91547,111774,4,YES,Good
436,NO,Divorced,98738,158057,4,YES,Good
437,YES,Married,21966,117250,20,YES,Risky
438,NO,Single,14398,74697,14,NO,Risky
439,YES,Divorced,18572,48956,8,NO,Risky
440,NO,Single,77312,170407,13,YES,Good
441,NO,Divorced,42074,70314,24,NO,Good
442,YES,Single,82799,193775,27,NO,Good
443,YES,Single,12659,189209,9,NO,Risky
444,YES,Single,19649,36956,14,NO,Risky
445,NO,Divorced,50119,128451,12,NO,Good
446,NO,Single,18888,65708,28,NO,Risky
447,NO,Married,83061,166606,5,YES,Good
448,YES,Single,39343,114597,28,YES,Good
449,NO,Married,92007,27875,11,NO,Good
450,YES,Divorced,78728,91936,8,YES,Good
451,YES,Divorced,48640,108262,10,YES,Good
452,NO,Single,92070,42620,10,NO,Good
453,YES,Single,97341,41504,26,NO,Good
454,NO,Married,97493,29602,15,YES,Good
455,NO,Married,78400,65533,23,YES,Good
456,NO,Single,52862,53788,23,YES,Good
457,NO,Married,11804,36055,24,YES,Risky
458,YES,Single,10455,110892,18,YES,Risky
459,YES,Divorced,25766,125407,21,NO,Risky
460,NO,Divorced,58199,54701,10,YES,Good
461,NO,Single,88613,163901,6,YES,Good
462,NO,Divorced,16690,149327,17,NO,Risky
463,NO,Divorced,71164,40460,3,YES,Good
464,NO,Married,48825,143349,16,YES,Good
465,NO,Divorced,29236,116282,21,NO,Risky
466,NO,Married,59689,186013,16,NO,Good
467,YES,Divorced,48940,106946,20,YES,Good
468,YES,Divorced,64320,38814,18,YES,Good
469,YES,Single,84845,65487,13,YES,Good
470,YES,Married,52663,148686,26,NO,Good
471,NO,Single,17957,192410,21,YES,Risky
472,NO,Married,69018,151963,11,YES,Good
473,YES,Single,58496,147367,16,YES,Good
474,YES,Divorced,99128,80729,0,NO,Good
475,NO,Single,35868,36081,12,YES,Good
476,NO,Single,79478,183057,7,YES,Good
477,YES,Divorced,57402,158849,29,NO,Good
478,NO,Divorced,73795,65242,6,NO,Good
479,YES,Married,58403,68995,21,NO,Good
480,NO,Divorced,85972,72252,26,YES,Good
481,YES,Single,62998,120012,13,NO,Good
482,NO,Single,32786,125771,12,NO,Good
483,NO,Single,17962,100961,10,NO,Risky
484,YES,Married,59440,114646,28,YES,Good
485,NO,Single,94772,52766,23,NO,Good
486,YES,Single,80083,57230,29,YES,Good
487,YES,Single,81026,83402,13,YES,Good
488,YES,Single,86883,76718,10,YES,Good
489,YES,Married,39444,148821,6,NO,Good
490,NO,Married,35886,120996,24,NO,Good
491,NO,Divorced,24541,82029,10,NO,Risky
492,YES,Single,54502,98123,18,YES,Good
493,NO,Married,17183,103226,29,NO,Risky
494,NO,Single,39562,197045,13,YES,Good
495,NO,Married,70157,59156,24,NO,Good
496,YES,Divorced,72151,59382,5,YES,Good
497,NO,Single,65170,100331,3,NO,Good
498,YES,Single,67936,164924,24,YES,Good
499,YES,Single,93339,48744,2,YES,Good
500,YES,Single,57365,158780,11,YES,Good
501,NO,Divorced,56628,55842,4,YES,Good
502,NO,Married,83814,53240,1,YES,Good
503,YES,Married,75324,81550,17,YES,Good
504,NO,Divorced,46939,198571,19,YES,Good
505,NO,Divorced,71428,74910,15,YES,Good
506,NO,Single,23884,111105,8,YES,Risky

In [8]:
#Drop the column which is not necessary for the futher procedure of DT use only sales criteria for classifying it
fraudcheck=fraudcheck.drop(['Taxable_income'],axis=1)
fraudcheck

,Undergrad,Marital.Status,City.Population,Work.Experience,Urban,Taxable_income1
0,NO,Single,50047,10,YES,Good
1,YES,Divorced,134075,18,YES,Good
2,NO,Married,160205,30,YES,Good
3,YES,Single,193264,15,YES,Good
4,NO,Married,27533,28,NO,Good
5,NO,Divorced,116382,0,NO,Good
6,NO,Divorced,80890,8,YES,Good
7,YES,Single,131253,3,YES,Good
8,NO,Single,102481,12,YES,Good
9,YES,Divorced,155482,4,YES,Good
10,NO,Single,102602,19,YES,Risky
11,NO,Single,94875,6,YES,Good
12,NO,Divorced,148033,14,YES,Risky
13,NO,Married,86649,16,YES,Good
14,NO,Married,57529,13,YES,Good
15,NO,Divorced,107764,29,NO,Good
16,YES,Divorced,34551,29,NO,Risky
17,YES,Married,57194,25,NO,Good
18,YES,Divorced,59269,6,NO,Good
19,NO,Single,126953,30,YES,Risky
20,YES,Single,147222,26,NO,Good
21,YES,Divorced,29106,7,YES,Risky
22,YES,Divorced,155342,14,NO,Good
23,NO,Single,50495,12,YES,Good
24,NO,Divorced,28495,30,NO,Good
25,NO,Divorced,124606,27,YES,Good
26,YES,Divorced,169128,15,NO,Good
27,YES,Single,28542,12,YES,Good
28,YES,Single,128766,5,YES,Risky
29,YES,Divorced,41863,30,YES,Good
30,YES,Divorced,117788,0,YES,Good
31,NO,Divorced,147414,21,NO,Good
32,YES,Married,51911,23,NO,Good
33,YES,Single,157251,21,NO,Good
34,YES,Divorced,183767,1,YES,Risky
35,YES,Married,41117,30,YES,Good
36,YES,Married,193995,5,YES,Risky
37,NO,Married,66912,5,YES,Good
38,NO,Single,177575,3,NO,Risky
39,NO,Married,54981,16,YES,Good
40,NO,Single,199697,26,YES,Good
41,YES,Married,91524,1,NO,Good
42,NO,Single,51666,12,NO,Good
43,YES,Divorced,50020,10,NO,Good
44,YES,Divorced,98880,22,NO,Good
45,YES,Married,183095,14,YES,Good
46,YES,Married,137346,27,YES,Good
47,YES,Single,34964,2,NO,Good
48,NO,Married,35480,12,NO,Risky
49,NO,Divorced,160195,15,YES,Good
50,YES,Single,145804,3,YES,Good
51,YES,Single,174042,30,NO,Good
52,NO,Single,91828,23,NO,Good
53,YES,Single,139143,7,YES,Risky
54,NO,Divorced,98207,23,NO,Good
55,YES,Single,89965,16,YES,Risky
56,NO,Married,69832,25,YES,Good
57,NO,Single,70744,13,NO,Good
58,YES,Single,158047,15,NO,Risky
59,NO,Single,102228,11,NO,Good
60,YES,Married,91138,23,NO,Good
61,YES,Married,86169,8,NO,Risky
62,NO,Divorced,147684,13,YES,Good
63,YES,Divorced,95831,9,NO,Good
64,YES,Single,118261,15,NO,Good
65,NO,Divorced,194738,29,NO,Good
66,YES,Married,66985,12,YES,Good
67,YES,Married,173986,24,NO,Good
68,NO,Single,139642,5,NO,Risky
69,YES,Single,86896,29,NO,Good
70,YES,Divorced,80904,3,YES,Good
71,NO,Single,105680,22,NO,Good
72,YES,Divorced,108300,27,YES,Good
73,YES,Single,174789,2,YES,Good
74,NO,Divorced,182319,17,NO,Good
75,NO,Married,50404,19,YES,Good
76,YES,Married,129164,11,NO,Good
77,YES,Married,118344,26,NO,Good
78,YES,Divorced,143153,0,NO,Good
79,NO,Divorced,140885,7,YES,Risky
80,NO,Married,28184,26,NO,Good
81,YES,Divorced,121608,24,NO,Good
82,NO,Divorced,111068,26,YES,Good
83,NO,Divorced,73963,18,YES,Good
84,NO,Married,178083,4,YES,Good
85,YES,Divorced,125155,12,YES,Risky
86,YES,Divorced,97520,29,YES,Good
87,YES,Single,64075,23,NO,Risky
88,NO,Married,63896,24,YES,Good
89,YES,Married,176050,20,NO,Risky
90,NO,Divorced,101232,29,NO,Good
91,YES,Married,73733,10,YES,Good
92,NO,Divorced,114621,13,NO,Good
93,YES,Married,137676,3,YES,Risky
94,NO,Single,122705,6,YES,Risky
95,YES,Single,121498,28,YES,Good
96,NO,Single,63622,17,NO,Risky
97,YES,Divorced,37849,19,YES,Good
98,YES,Married,77053,18,YES,Risky
99,NO,Married,114350,12,NO,Good
100,YES,Single,46444,25,NO,Good
101,YES,Married,50490,20,YES,Good
102,YES,Divorced,91488,23,NO,Good
103,NO,Divorced,76318,5,YES,Good
104,NO,Single,174423,14,NO,Good
105,NO,Single,46893,15,NO,Good
106,YES,Single,58535,20,YES,Risky
107,NO,Married,52424,6,YES,Good
108,YES,Married,120894,10,YES,Good
109,YES,Married,178585,8,YES,Good
110,NO,Single,32450,19,YES,Risky
111,NO,Single,164526,11,YES,Good
112,YES,Single,193038,26,YES,Good
113,YES,Married,100347,7,YES,Good
114,NO,Single,197934,7,NO,Risky
115,YES,Divorced,78251,21,YES,Good
116,NO,Married,132570,12,NO,Good
117,NO,Single,96370,29,YES,Good
118,NO,Divorced,199174,10,NO,Risky
119,NO,Divorced,47202,30,YES,Good
120,YES,Single,135886,11,YES,Good
121,YES,Married,86648,16,YES,Risky
122,YES,Married,140762,26,NO,Risky
123,YES,Married,79683,26,NO,Risky
124,YES,Divorced,139324,13,NO,Good
125,YES,Divorced,155669,11,NO,Good
126,YES,Divorced,195022,3,YES,Risky
127,NO,Single,93035,28,YES,Good
128,NO,Married,100897,27,YES,Good
129,YES,Single,65469,26,NO,Good
130,YES,Single,87730,7,YES,Good
131,YES,Single,174321,16,YES,Good
132,NO,Divorced,67820,12,NO,Good
133,NO,Single,86646,14,YES,Good
134,YES,Married,190365,28,NO,Good
135,YES,Divorced,75323,19,YES,Risky
136,NO,Divorced,53513,9,NO,Good
137,YES,Single,115884,6,NO,Risky
138,NO,Single,155335,25,NO,Good
139,YES,Divorced,86904,20,NO,Good
140,YES,Married,93390,4,YES,Risky
141,YES,Married,194364,23,YES,Good
142,NO,Single,122654,26,YES,Good
143,YES,Single,154013,11,NO,Risky
144,YES,Single,156503,29,YES,Good
145,NO,Divorced,197422,2,YES,Good
146,NO,Divorced,57931,28,YES,Good
147,YES,Divorced,163252,28,NO,Good
148,NO,Married,197038,21,NO,Good
149,NO,Single,49505,25,NO,Good
150,NO,Married,161759,28,NO,Good
151,NO,Single,109110,10,NO,Good
152,NO,Single,91889,16,NO,Risky
153,YES,Divorced,114841,28,NO,Risky
154,NO,Single,82520,29,YES,Risky
155,YES,Single,139624,7,NO,Good
156,YES,Married,125987,3,YES,Good
157,YES,Married,115631,5,NO,Good
158,NO,Divorced,163347,11,NO,Risky
159,YES,Single,28504,1,NO,Good
160,YES,Divorced,79972,0,YES,Good
161,YES,Married,185596,30,YES,Good
162,YES,Married,177468,21,YES,Good
163,YES,Divorced,91851,15,YES,Risky
164,YES,Single,153192,28,NO,Good
165,YES,Married,38463,23,YES,Good
166,NO,Married,73466,22,YES,Good
167,NO,Married,194381,25,NO,Good
168,NO,Divorced,167629,30,NO,Risky
169,YES,Single,76933,6,YES,Good
170,NO,Divorced,143402,10,NO,Good
171,YES,Married,103614,24,NO,Risky
172,NO,Married,52819,23,YES,Risky
173,YES,Single,105110,16,YES,Good
174,YES,Single,149857,8,NO,Good
175,YES,Single,57055,13,NO,Good
176,NO,Married,75169,28,NO,Good
177,NO,Married,31156,13,YES,Good
178,NO,Single,85832,15,YES,Good
179,YES,Married,192451,22,YES,Risky
180,YES,Single,149101,19,NO,Good
181,NO,Divorced,36116,20,NO,Risky
182,NO,Divorced,89632,4,YES,Risky
183,NO,Single,39523,30,YES,Good
184,NO,Divorced,70138,15,YES,Good
185,NO,Married,92975,0,YES,Good
186,NO,Married,166976,19,YES,Good
187,NO,Single,59558,5,YES,Good
188,NO,Divorced,137569,10,NO,Risky
189,YES,Married,189301,11,YES,Good
190,NO,Single,90459,19,NO,Good
191,NO,Single,176341,7,YES,Good
192,YES,Married,126556,10,YES,Good
193,YES,Married,198213,25,NO,Good
194,YES,Single,103981,28,NO,Risky
195,YES,Single,181370,13,YES,Good
196,YES,Married,28410,21,NO,Risky
197,NO,Single,98056,4,YES,Good
198,NO,Single,48025,28,YES,Good
199,YES,Married,145744,9,YES,Risky
200,YES,Single,162777,17,YES,Good
201,YES,Divorced,58225,27,YES,Good
202,YES,Single,28661,0,YES,Good
203,YES,Divorced,117260,4,NO,Good
204,NO,Married,173091,14,NO,Risky
205,NO,Married,131906,20,YES,Risky
206,YES,Single,52227,16,YES,Good
207,YES,Married,138108,28,NO,Risky
208,YES,Single,141502,3,NO,Good
209,YES,Single,186239,25,YES,Good
210,YES,Single,125993,13,YES,Good
211,YES,Married,57194,8,YES,Good
212,YES,Divorced,112659,14,NO,Good
213,YES,Single,107069,13,NO,Good
214,NO,Divorced,140159,16,NO,Good
215,NO,Divorced,28576,22,NO,Good
216,NO,Divorced,85128,22,NO,Good
217,YES,Divorced,179220,19,YES,Good
218,NO,Married,38091,19,NO,Good
219,YES,Divorced,26814,9,NO,Risky
220,YES,Divorced,115168,30,NO,Good
221,YES,Single,134135,14,NO,Good
222,YES,Divorced,168248,27,NO,Good
223,YES,Married,192297,17,YES,Good
224,NO,Married,55717,25,YES,Good
225,YES,Single,125883,0,YES,Good
226,NO,Single,77719,28,NO,Good
227,YES,Single,182921,17,YES,Good
228,NO,Married,100696,9,YES,Risky
229,NO,Married,35780,10,NO,Good
230,NO,Married,81593,14,YES,Risky
231,YES,Single,153147,2,NO,Good
232,YES,Married,150349,2,NO,Risky
233,NO,Married,63701,19,YES,NaN
234,NO,Single,102498,14,NO,Good
235,NO,Divorced,87541,9,NO,Good
236,YES,Married,193193,3,NO,Good
237,NO,Married,128996,3,YES,Risky
238,YES,Single,72968,9,YES,Good
239,NO,Divorced,76145,26,NO,Good
240,NO,Single,139146,30,YES,Good
241,YES,Single,31377,18,YES,Risky
242,NO,Divorced,84368,2,YES,Good
243,NO,Divorced,181549,10,YES,Good
244,YES,Single,154647,27,NO,Good
245,NO,Single,183221,24,NO,Good
246,YES,Single,38139,25,NO,Good
247,YES,Divorced,108245,1,NO,Risky
248,NO,Single,105374,17,YES,Risky
249,YES,Single,35376,0,YES,Good
250,NO,Married,156973,16,NO,Good
251,YES,Single,173228,7,NO,Good
252,NO,Single,40855,28,YES,Good
253,YES,Single,77256,29,NO,Good
254,NO,Divorced,193263,26,NO,Good
255,YES,Married,170030,8,NO,Good
256,YES,Married,168568,14,NO,Good
257,YES,Married,31611,17,YES,Good
258,NO,Divorced,74119,28,YES,Good
259,NO,Married,197841,7,NO,Risky
260,YES,Single,92333,28,NO,Good
261,NO,Single,68788,7,YES,Good
262,NO,Divorced,120415,21,NO,Good
263,YES,Married,69386,21,YES,Good
264,NO,Single,118899,5,NO,Good
265,NO,Married,101996,4,YES,Risky
266,YES,Married,173276,17,YES,Good
267,NO,Single,183946,11,NO,Risky
268,NO,Single,98378,3,YES,Good
269,YES,Married,125450,13,YES,Good
270,NO,Married,130680,5,NO,Good
271,NO,Single,183682,20,NO,Good
272,NO,Single,126488,1,YES,Good
273,YES,Divorced,58942,20,NO,Good
274,YES,Married,112584,25,NO,Good
275,YES,Married,55591,0,YES,Good
276,NO,Single,44251,17,YES,Good
277,NO,Divorced,117364,11,NO,Good
278,NO,Married,114823,11,NO,Risky
279,YES,Single,74136,12,YES,Good
280,NO,Divorced,33184,1,NO,Risky
281,NO,Single,167403,7,YES,Good
282,YES,Married,59590,29,NO,Good
283,YES,Divorced,129276,22,NO,Good
284,NO,Divorced,188383,22,YES,Risky
285,NO,Single,63420,10,NO,Good
286,YES,Divorced,113724,6,NO,Good
287,YES,Single,77102,1,YES,Good
288,YES,Married,174196,21,YES,Risky
289,NO,Single,196816,14,NO,Good
290,YES,Married,193003,30,YES,Good
291,YES,Single,62475,26,YES,Good
292,YES,Single,76406,1,YES,Risky
293,NO,Divorced,43899,21,YES,Good
294,YES,Single,74074,2,NO,Good
295,YES,Married,40089,10,NO,Good
296,YES,Divorced,167600,26,NO,Good
297,NO,Married,36924,15,NO,Good
298,NO,Single,119904,21,YES,Good
299,YES,Single,197916,7,NO,Good
300,NO,Married,74052,30,NO,Good
301,YES,Married,39797,11,NO,Risky
302,YES,Divorced,97109,27,NO,Good
303,YES,Divorced,189061,13,YES,Good
304,YES,Divorced,106757,23,YES,Good
305,NO,Single,161265,29,YES,Good
306,YES,Divorced,185099,12,NO,Good
307,NO,Divorced,31819,25,NO,Good
308,YES,Married,183445,30,NO,Good
309,YES,Single,123761,20,YES,Good
310,YES,Divorced,189435,22,YES,Good
311,NO,Married,50013,19,NO,Good
312,YES,Single,31641,18,NO,Good
313,YES,Single,124848,2,NO,Good
314,NO,Single,85255,4,NO,Good
315,YES,Divorced,176278,19,NO,Risky
316,NO,Married,70323,25,NO,Good
317,YES,Married,116745,23,NO,Good
318,NO,Divorced,121324,14,YES,Good
319,YES,Divorced,153308,24,YES,Good
320,YES,Single,78897,11,YES,Good
321,NO,Single,84215,6,YES,Good
322,NO,Divorced,160932,24,YES,Good
323,YES,Married,165175,13,NO,Good
324,YES,Single,171288,15,NO,Good
325,NO,Single,25779,16,YES,Good
326,YES,Divorced,165001,19,YES,Risky
327,YES,Married,162777,7,NO,Risky
328,NO,Divorced,93414,12,YES,Good
329,NO,Single,39360,10,NO,Risky
330,NO,Married,43176,29,NO,Good
331,YES,Married,60999,15,YES,Risky
332,YES,Divorced,84132,1,NO,Good
333,YES,Single,44775,13,YES,Risky
334,NO,Single,118274,13,YES,Good
335,YES,Married,140998,15,NO,Good
336,NO,Married,73146,5,NO,Good
337,YES,Married,73490,7,NO,Risky
338,YES,Divorced,111264,23,NO,Risky
339,YES,Single,110940,10,NO,Risky
340,YES,Married,54437,21,YES,Good
341,NO,Married,83900,8,YES,Good
342,YES,Married,31097,7,YES,Good
343,YES,Divorced,161143,17,NO,Good
344,NO,Married,192313,5,YES,Good
345,YES,Divorced,118798,6,NO,Good
346,NO,Single,134635,30,YES,Risky
347,NO,Married,80991,0,YES,Risky
348,YES,Single,42269,2,NO,Good
349,YES,Divorced,72255,30,YES,Risky
350,NO,Married,89949,25,NO,Good
351,YES,Married,114922,12,NO,Good
352,NO,Divorced,72115,16,YES,Risky
353,YES,Married,141622,29,NO,Good
354,YES,Married,176891,27,YES,Risky
355,YES,Single,56488,17,NO,Good
356,NO,Married,46480,27,NO,Risky
357,NO,Married,84034,28,NO,Risky
358,YES,Single,96432,24,YES,Good
359,YES,Single,157299,11,NO,Good
360,YES,Single,107937,5,YES,Good
361,YES,Divorced,62671,20,NO,Good
362,YES,Divorced,75552,17,YES,Risky
363,YES,Single,52584,7,YES,Risky
364,YES,Married,62943,17,NO,Good
365,NO,Divorced,134321,10,YES,Good
366,YES,Married,131469,30,NO,Good
367,YES,Married,95404,24,YES,Risky
368,YES,Divorced,128428,14,NO,Good
369,NO,Married,89122,28,NO,Good
370,NO,Divorced,86119,5,YES,Good
371,YES,Single,75580,5,NO,Good
372,YES,Married,168473,9,NO,Good
373,NO,Married,175719,21,YES,Good
374,YES,Divorced,147614,9,YES,Good
375,NO,Married,130935,2,NO,Good
376,NO,Divorced,188067,26,NO,Good
377,YES,Single,103490,30,NO,Good
378,YES,Divorced,152471,6,NO,Good
379,NO,Single,112774,13,NO,Risky
380,YES,Married,197699,2,NO,Good
381,NO,Single,61920,4,NO,Good
382,YES,Divorced,139269,29,NO,Good
383,YES,Married,148246,5,YES,Good
384,YES,Married,147346,25,NO,Good
385,NO,Single,140132,27,NO,Good
386,NO,Single,140642,27,YES,Good
387,YES,Single,56597,9,YES,Good
388,YES,Divorced,151636,4,YES,Good
389,YES,Single,183187,5,YES,Good
390,YES,Single,57324,17,NO,Good
391,NO,Married,29934,1,NO,Good
392,YES,Divorced,37776,15,NO,Risky
393,NO,Married,68687,30,YES,Good
394,NO,Divorced,64990,21,YES,Good
395,YES,Single,183094,5,NO,Good
396,YES,Single,176330,21,NO,Good
397,NO,Married,91689,14,YES,Good
398,NO,Married,64070,2,YES,Risky
399,NO,Single,74497,21,NO,Good
400,YES,Married,197421,16,NO,Good
401,NO,Married,73065,20,NO,Good
402,YES,Divorced,105376,11,NO,Good
403,NO,Divorced,130912,27,YES,Good
404,YES,Divorced,34334,21,YES,Good
405,NO,Divorced,140266,28,NO,Good
406,NO,Married,107688,2,NO,Good
407,NO,Single,52144,6,NO,Good
408,YES,Divorced,77059,22,NO,Good
409,NO,Single,163058,1,NO,Good
410,NO,Divorced,41152,27,NO,Good
411,NO,Married,46253,19,NO,Good
412,YES,Single,28446,11,NO,Good
413,YES,Single,112890,11,YES,Good
414,NO,Divorced,27300,1,YES,Good
415,NO,Divorced,131493,21,NO,Good
416,NO,Single,33982,30,NO,Good
417,NO,Divorced,76625,2,NO,Good
418,YES,Divorced,104183,18,NO,Good
419,NO,Married,138074,20,NO,Good
420,NO,Divorced,84473,2,NO,Good
421,YES,Single,135185,13,NO,Good
422,NO,Divorced,191983,14,YES,Good
423,NO,Married,80249,19,YES,Good
424,YES,Married,94199,0,YES,Good
425,YES,Divorced,121506,27,NO,Good
426,YES,Divorced,50373,25,YES,Good
427,NO,Divorced,99025,10,NO,Good
428,YES,Married,128266,24,YES,Risky
429,NO,Single,153748,30,YES,Good
430,YES,Married,161215,8,NO,Good
431,NO,Single,168360,25,YES,Good
432,NO,Married,157217,11,YES,Good
433,NO,Married,129265,14,YES,Risky
434,YES,Single,87188,19,YES,Risky
435,NO,Divorced,111774,4,YES,Good
436,NO,Divorced,158057,4,YES,Good
437,YES,Married,117250,20,YES,Risky
438,NO,Single,74697,14,NO,Risky
439,YES,Divorced,48956,8,NO,Risky
440,NO,Single,170407,13,YES,Good
441,NO,Divorced,70314,24,NO,Good
442,YES,Single,193775,27,NO,Good
443,YES,Single,189209,9,NO,Risky
444,YES,Single,36956,14,NO,Risky
445,NO,Divorced,128451,12,NO,Good
446,NO,Single,65708,28,NO,Risky
447,NO,Married,166606,5,YES,Good
448,YES,Single,114597,28,YES,Good
449,NO,Married,27875,11,NO,Good
450,YES,Divorced,91936,8,YES,Good
451,YES,Divorced,108262,10,YES,Good
452,NO,Single,42620,10,NO,Good
453,YES,Single,41504,26,NO,Good
454,NO,Married,29602,15,YES,Good
455,NO,Married,65533,23,YES,Good
456,NO,Single,53788,23,YES,Good
457,NO,Married,36055,24,YES,Risky
458,YES,Single,110892,18,YES,Risky
459,YES,Divorced,125407,21,NO,Risky
460,NO,Divorced,54701,10,YES,Good
461,NO,Single,163901,6,YES,Good
462,NO,Divorced,149327,17,NO,Risky
463,NO,Divorced,40460,3,YES,Good
464,NO,Married,143349,16,YES,Good
465,NO,Divorced,116282,21,NO,Risky
466,NO,Married,186013,16,NO,Good
467,YES,Divorced,106946,20,YES,Good
468,YES,Divorced,38814,18,YES,Good
469,YES,Single,65487,13,YES,Good
470,YES,Married,148686,26,NO,Good
471,NO,Single,192410,21,YES,Risky
472,NO,Married,151963,11,YES,Good
473,YES,Single,147367,16,YES,Good
474,YES,Divorced,80729,0,NO,Good
475,NO,Single,36081,12,YES,Good
476,NO,Single,183057,7,YES,Good
477,YES,Divorced,158849,29,NO,Good
478,NO,Divorced,65242,6,NO,Good
479,YES,Married,68995,21,NO,Good
480,NO,Divorced,72252,26,YES,Good
481,YES,Single,120012,13,NO,Good
482,NO,Single,125771,12,NO,Good
483,NO,Single,100961,10,NO,Risky
484,YES,Married,114646,28,YES,Good
485,NO,Single,52766,23,NO,Good
486,YES,Single,57230,29,YES,Good
487,YES,Single,83402,13,YES,Good
488,YES,Single,76718,10,YES,Good
489,YES,Married,148821,6,NO,Good
490,NO,Married,120996,24,NO,Good
491,NO,Divorced,82029,10,NO,Risky
492,YES,Single,98123,18,YES,Good
493,NO,Married,103226,29,NO,Risky
494,NO,Single,197045,13,YES,Good
495,NO,Married,59156,24,NO,Good
496,YES,Divorced,59382,5,YES,Good
497,NO,Single,100331,3,NO,Good
498,YES,Single,164924,24,YES,Good
499,YES,Single,48744,2,YES,Good
500,YES,Single,158780,11,YES,Good
501,NO,Divorced,55842,4,YES,Good
502,NO,Married,53240,1,YES,Good
503,YES,Married,81550,17,YES,Good
504,NO,Divorced,198571,19,YES,Good
505,NO,Divorced,74910,15,YES,Good
506,NO,Single,111105,8,YES,Risky
507,YES,Single,101272,24,YES,Good
508,NO,Single,195357,19,NO,Good
509,NO,Married,65531,27,YES,Risky
510,YES,Married,75436,14,YES,Good
511,NO,Married,153233,5,YES,Good
512,YES,Single,137948,22,YES,Good
513,NO,Divorced,140400,10,NO,Good
514,NO,Divorced,31380,6,NO,Good
515,NO,Divorced,87868,13,NO,Good
516,YES,Single,76337,18,YES,Good
517,NO,Single,195078,26,NO,Risky
518,YES,Single,112591,26,YES,Good
519,YES,Single,162102,25,YES,Good
520,NO,Divorced,142426,8,YES,Good
521,NO,Divorced,51104,15,NO,Good
522,NO,Divorced,103343,10,NO,Good
523,NO,Divorced,42198,12,NO,Good
524,YES,Married,164391,27,NO,Risky
525,YES,Single,75307,23,NO,Good
526,NO,Divorced,82565,12,NO,Risky
527,NO,Married,180274,27,NO,Good
528,NO,Married,172612,10,NO,Good
529,NO,Divorced,83388,14,NO,Good
530,YES,Divorced,194421,17,YES,Good
531,YES,Married,124440,14,YES,Good
532,YES,Divorced,98662,16,NO,Good
533,NO,Divorced,54113,19,YES,Risky
534,YES,Married,91567,13,YES,Good
535,NO,Married,189851,3,NO,Good
536,NO,Single,157025,14,NO,Good
537,YES,Single,100651,6,NO,Good
538,NO,Married,119976,12,NO,Good
539,YES,Divorced,57390,8,NO,Good
540,YES,Single,110308,22,NO,Risky
541,YES,Divorced,191874,30,YES,Risky
542,YES,Married,199778,27,NO,Good
543,NO,Single,130816,13,NO,Good
544,NO,Single,133877,21,YES,Risky
545,YES,Divorced,109079,8,NO,Good
546,NO,Married,59091,6,NO,Good
547,YES,Single,42690,25,YES,Good
548,YES,Divorced,154393,9,YES,Good
549,NO,Married,74058,11,YES,Good
550,NO,Married,68160,2,YES,Good
551,YES,Married,123082,0,YES,Good
552,NO,Single,109191,5,YES,Good
553,NO,Single,26884,13,YES,Good
554,NO,Divorced,147788,27,NO,Good
555,NO,Single,53848,10,NO,Good
556,NO,Single,34242,12,NO,Good
557,YES,Married,157421,10,NO,Risky
558,NO,Divorced,191139,12,YES,Good
559,YES,Divorced,180424,26,NO,Good
560,NO,Divorced,182562,24,NO,Good
561,NO,Married,36861,29,YES,Good
562,YES,Divorced,100064,12,NO,Good
563,YES,Married,116495,6,YES,Good
564,YES,Married,30098,11,YES,Good
565,NO,Divorced,31064,28,NO,Good
566,NO,Married,33460,28,NO,Good
567,YES,Single,129912,30,NO,Risky
568,NO,Single,150036,22,YES,Good
569,YES,Single,38074,12,YES,Good
570,NO,Single,161629,29,YES,Good
571,NO,Single,95421,7,YES,Good
572,YES,Married,148068,13,NO,Good
573,YES,Married,116161,20,NO,Good
574,YES,Divorced,28768,29,YES,Good
575,NO,Divorced,95975,13,YES,Risky
576,YES,Married,79653,15,YES,Good
577,YES,Married,52940,5,YES,Good
578,NO,Divorced,185339,6,NO,Good
579,YES,Single,125112,7,YES,Good
580,YES,Divorced,123335,1,YES,Good
581,YES,Divorced,57473,10,YES,Good
582,YES,Married,32907,12,YES,Good
583,NO,Married,28874,19,NO,Good
584,NO,Divorced,155684,4,YES,Good
585,NO,Single,137622,2,YES,Good
586,YES,Single,106230,30,NO,Good
587,NO,Single,154677,26,YES,Good
588,YES,Married,93242,27,YES,Good
589,YES,Married,30774,10,NO,Good
590,NO,Married,85195,14,YES,Good
591,YES,Single,132859,18,YES,Risky
592,YES,Single,75143,16,NO,Good
593,NO,Divorced,131963,10,YES,Good
594,NO,Married,97526,9,YES,Good
595,YES,Divorced,39492,7,YES,Good
596,YES,Divorced,55369,2,YES,Good
597,NO,Divorced,154058,0,YES,Good

In [9]:
#Rename the column
fraudcheck=fraudcheck.rename({"Taxable_income1":"Taxable_income","Marital.Status":"Marital_status","Work.Experience":"Work_experience","City.Population":"City_population"},axis=1)
fraudcheck

,Undergrad,Marital_status,City_population,Work_experience,Urban,Taxable_income
0,NO,Single,50047,10,YES,Good
1,YES,Divorced,134075,18,YES,Good
2,NO,Married,160205,30,YES,Good
3,YES,Single,193264,15,YES,Good
4,NO,Married,27533,28,NO,Good
5,NO,Divorced,116382,0,NO,Good
6,NO,Divorced,80890,8,YES,Good
7,YES,Single,131253,3,YES,Good
8,NO,Single,102481,12,YES,Good
9,YES,Divorced,155482,4,YES,Good
10,NO,Single,102602,19,YES,Risky
11,NO,Single,94875,6,YES,Good
12,NO,Divorced,148033,14,YES,Risky
13,NO,Married,86649,16,YES,Good
14,NO,Married,57529,13,YES,Good
15,NO,Divorced,107764,29,NO,Good
16,YES,Divorced,34551,29,NO,Risky
17,YES,Married,57194,25,NO,Good
18,YES,Divorced,59269,6,NO,Good
19,NO,Single,126953,30,YES,Risky
20,YES,Single,147222,26,NO,Good
21,YES,Divorced,29106,7,YES,Risky
22,YES,Divorced,155342,14,NO,Good
23,NO,Single,50495,12,YES,Good
24,NO,Divorced,28495,30,NO,Good
25,NO,Divorced,124606,27,YES,Good
26,YES,Divorced,169128,15,NO,Good
27,YES,Single,28542,12,YES,Good
28,YES,Single,128766,5,YES,Risky
29,YES,Divorced,41863,30,YES,Good
30,YES,Divorced,117788,0,YES,Good
31,NO,Divorced,147414,21,NO,Good
32,YES,Married,51911,23,NO,Good
33,YES,Single,157251,21,NO,Good
34,YES,Divorced,183767,1,YES,Risky
35,YES,Married,41117,30,YES,Good
36,YES,Married,193995,5,YES,Risky
37,NO,Married,66912,5,YES,Good
38,NO,Single,177575,3,NO,Risky
39,NO,Married,54981,16,YES,Good
40,NO,Single,199697,26,YES,Good
41,YES,Married,91524,1,NO,Good
42,NO,Single,51666,12,NO,Good
43,YES,Divorced,50020,10,NO,Good
44,YES,Divorced,98880,22,NO,Good
45,YES,Married,183095,14,YES,Good
46,YES,Married,137346,27,YES,Good
47,YES,Single,34964,2,NO,Good
48,NO,Married,35480,12,NO,Risky
49,NO,Divorced,160195,15,YES,Good
50,YES,Single,145804,3,YES,Good
51,YES,Single,174042,30,NO,Good
52,NO,Single,91828,23,NO,Good
53,YES,Single,139143,7,YES,Risky
54,NO,Divorced,98207,23,NO,Good
55,YES,Single,89965,16,YES,Risky
56,NO,Married,69832,25,YES,Good
57,NO,Single,70744,13,NO,Good
58,YES,Single,158047,15,NO,Risky
59,NO,Single,102228,11,NO,Good
60,YES,Married,91138,23,NO,Good
61,YES,Married,86169,8,NO,Risky
62,NO,Divorced,147684,13,YES,Good
63,YES,Divorced,95831,9,NO,Good
64,YES,Single,118261,15,NO,Good
65,NO,Divorced,194738,29,NO,Good
66,YES,Married,66985,12,YES,Good
67,YES,Married,173986,24,NO,Good
68,NO,Single,139642,5,NO,Risky
69,YES,Single,86896,29,NO,Good
70,YES,Divorced,80904,3,YES,Good
71,NO,Single,105680,22,NO,Good
72,YES,Divorced,108300,27,YES,Good
73,YES,Single,174789,2,YES,Good
74,NO,Divorced,182319,17,NO,Good
75,NO,Married,50404,19,YES,Good
76,YES,Married,129164,11,NO,Good
77,YES,Married,118344,26,NO,Good
78,YES,Divorced,143153,0,NO,Good
79,NO,Divorced,140885,7,YES,Risky
80,NO,Married,28184,26,NO,Good
81,YES,Divorced,121608,24,NO,Good
82,NO,Divorced,111068,26,YES,Good
83,NO,Divorced,73963,18,YES,Good
84,NO,Married,178083,4,YES,Good
85,YES,Divorced,125155,12,YES,Risky
86,YES,Divorced,97520,29,YES,Good
87,YES,Single,64075,23,NO,Risky
88,NO,Married,63896,24,YES,Good
89,YES,Married,176050,20,NO,Risky
90,NO,Divorced,101232,29,NO,Good
91,YES,Married,73733,10,YES,Good
92,NO,Divorced,114621,13,NO,Good
93,YES,Married,137676,3,YES,Risky
94,NO,Single,122705,6,YES,Risky
95,YES,Single,121498,28,YES,Good
96,NO,Single,63622,17,NO,Risky
97,YES,Divorced,37849,19,YES,Good
98,YES,Married,77053,18,YES,Risky
99,NO,Married,114350,12,NO,Good
100,YES,Single,46444,25,NO,Good
101,YES,Married,50490,20,YES,Good
102,YES,Divorced,91488,23,NO,Good
103,NO,Divorced,76318,5,YES,Good
104,NO,Single,174423,14,NO,Good
105,NO,Single,46893,15,NO,Good
106,YES,Single,58535,20,YES,Risky
107,NO,Married,52424,6,YES,Good
108,YES,Married,120894,10,YES,Good
109,YES,Married,178585,8,YES,Good
110,NO,Single,32450,19,YES,Risky
111,NO,Single,164526,11,YES,Good
112,YES,Single,193038,26,YES,Good
113,YES,Married,100347,7,YES,Good
114,NO,Single,197934,7,NO,Risky
115,YES,Divorced,78251,21,YES,Good
116,NO,Married,132570,12,NO,Good
117,NO,Single,96370,29,YES,Good
118,NO,Divorced,199174,10,NO,Risky
119,NO,Divorced,47202,30,YES,Good
120,YES,Single,135886,11,YES,Good
121,YES,Married,86648,16,YES,Risky
122,YES,Married,140762,26,NO,Risky
123,YES,Married,79683,26,NO,Risky
124,YES,Divorced,139324,13,NO,Good
125,YES,Divorced,155669,11,NO,Good
126,YES,Divorced,195022,3,YES,Risky
127,NO,Single,93035,28,YES,Good
128,NO,Married,100897,27,YES,Good
129,YES,Single,65469,26,NO,Good
130,YES,Single,87730,7,YES,Good
131,YES,Single,174321,16,YES,Good
132,NO,Divorced,67820,12,NO,Good
133,NO,Single,86646,14,YES,Good
134,YES,Married,190365,28,NO,Good
135,YES,Divorced,75323,19,YES,Risky
136,NO,Divorced,53513,9,NO,Good
137,YES,Single,115884,6,NO,Risky
138,NO,Single,155335,25,NO,Good
139,YES,Divorced,86904,20,NO,Good
140,YES,Married,93390,4,YES,Risky
141,YES,Married,194364,23,YES,Good
142,NO,Single,122654,26,YES,Good
143,YES,Single,154013,11,NO,Risky
144,YES,Single,156503,29,YES,Good
145,NO,Divorced,197422,2,YES,Good
146,NO,Divorced,57931,28,YES,Good
147,YES,Divorced,163252,28,NO,Good
148,NO,Married,197038,21,NO,Good
149,NO,Single,49505,25,NO,Good
150,NO,Married,161759,28,NO,Good
151,NO,Single,109110,10,NO,Good
152,NO,Single,91889,16,NO,Risky
153,YES,Divorced,114841,28,NO,Risky
154,NO,Single,82520,29,YES,Risky
155,YES,Single,139624,7,NO,Good
156,YES,Married,125987,3,YES,Good
157,YES,Married,115631,5,NO,Good
158,NO,Divorced,163347,11,NO,Risky
159,YES,Single,28504,1,NO,Good
160,YES,Divorced,79972,0,YES,Good
161,YES,Married,185596,30,YES,Good
162,YES,Married,177468,21,YES,Good
163,YES,Divorced,91851,15,YES,Risky
164,YES,Single,153192,28,NO,Good
165,YES,Married,38463,23,YES,Good
166,NO,Married,73466,22,YES,Good
167,NO,Married,194381,25,NO,Good
168,NO,Divorced,167629,30,NO,Risky
169,YES,Single,76933,6,YES,Good
170,NO,Divorced,143402,10,NO,Good
171,YES,Married,103614,24,NO,Risky
172,NO,Married,52819,23,YES,Risky
173,YES,Single,105110,16,YES,Good
174,YES,Single,149857,8,NO,Good
175,YES,Single,57055,13,NO,Good
176,NO,Married,75169,28,NO,Good
177,NO,Married,31156,13,YES,Good
178,NO,Single,85832,15,YES,Good
179,YES,Married,192451,22,YES,Risky
180,YES,Single,149101,19,NO,Good
181,NO,Divorced,36116,20,NO,Risky
182,NO,Divorced,89632,4,YES,Risky
183,NO,Single,39523,30,YES,Good
184,NO,Divorced,70138,15,YES,Good
185,NO,Married,92975,0,YES,Good
186,NO,Married,166976,19,YES,Good
187,NO,Single,59558,5,YES,Good
188,NO,Divorced,137569,10,NO,Risky
189,YES,Married,189301,11,YES,Good
190,NO,Single,90459,19,NO,Good
191,NO,Single,176341,7,YES,Good
192,YES,Married,126556,10,YES,Good
193,YES,Married,198213,25,NO,Good
194,YES,Single,103981,28,NO,Risky
195,YES,Single,181370,13,YES,Good
196,YES,Married,28410,21,NO,Risky
197,NO,Single,98056,4,YES,Good
198,NO,Single,48025,28,YES,Good
199,YES,Married,145744,9,YES,Risky
200,YES,Single,162777,17,YES,Good
201,YES,Divorced,58225,27,YES,Good
202,YES,Single,28661,0,YES,Good
203,YES,Divorced,117260,4,NO,Good
204,NO,Married,173091,14,NO,Risky
205,NO,Married,131906,20,YES,Risky
206,YES,Single,52227,16,YES,Good
207,YES,Married,138108,28,NO,Risky
208,YES,Single,141502,3,NO,Good
209,YES,Single,186239,25,YES,Good
210,YES,Single,125993,13,YES,Good
211,YES,Married,57194,8,YES,Good
212,YES,Divorced,112659,14,NO,Good
213,YES,Single,107069,13,NO,Good
214,NO,Divorced,140159,16,NO,Good
215,NO,Divorced,28576,22,NO,Good
216,NO,Divorced,85128,22,NO,Good
217,YES,Divorced,179220,19,YES,Good
218,NO,Married,38091,19,NO,Good
219,YES,Divorced,26814,9,NO,Risky
220,YES,Divorced,115168,30,NO,Good
221,YES,Single,134135,14,NO,Good
222,YES,Divorced,168248,27,NO,Good
223,YES,Married,192297,17,YES,Good
224,NO,Married,55717,25,YES,Good
225,YES,Single,125883,0,YES,Good
226,NO,Single,77719,28,NO,Good
227,YES,Single,182921,17,YES,Good
228,NO,Married,100696,9,YES,Risky
229,NO,Married,35780,10,NO,Good
230,NO,Married,81593,14,YES,Risky
231,YES,Single,153147,2,NO,Good
232,YES,Married,150349,2,NO,Risky
233,NO,Married,63701,19,YES,NaN
234,NO,Single,102498,14,NO,Good
235,NO,Divorced,87541,9,NO,Good
236,YES,Married,193193,3,NO,Good
237,NO,Married,128996,3,YES,Risky
238,YES,Single,72968,9,YES,Good
239,NO,Divorced,76145,26,NO,Good
240,NO,Single,139146,30,YES,Good
241,YES,Single,31377,18,YES,Risky
242,NO,Divorced,84368,2,YES,Good
243,NO,Divorced,181549,10,YES,Good
244,YES,Single,154647,27,NO,Good
245,NO,Single,183221,24,NO,Good
246,YES,Single,38139,25,NO,Good
247,YES,Divorced,108245,1,NO,Risky
248,NO,Single,105374,17,YES,Risky
249,YES,Single,35376,0,YES,Good
250,NO,Married,156973,16,NO,Good
251,YES,Single,173228,7,NO,Good
252,NO,Single,40855,28,YES,Good
253,YES,Single,77256,29,NO,Good
254,NO,Divorced,193263,26,NO,Good
255,YES,Married,170030,8,NO,Good
256,YES,Married,168568,14,NO,Good
257,YES,Married,31611,17,YES,Good
258,NO,Divorced,74119,28,YES,Good
259,NO,Married,197841,7,NO,Risky
260,YES,Single,92333,28,NO,Good
261,NO,Single,68788,7,YES,Good
262,NO,Divorced,120415,21,NO,Good
263,YES,Married,69386,21,YES,Good
264,NO,Single,118899,5,NO,Good
265,NO,Married,101996,4,YES,Risky
266,YES,Married,173276,17,YES,Good
267,NO,Single,183946,11,NO,Risky
268,NO,Single,98378,3,YES,Good
269,YES,Married,125450,13,YES,Good
270,NO,Married,130680,5,NO,Good
271,NO,Single,183682,20,NO,Good
272,NO,Single,126488,1,YES,Good
273,YES,Divorced,58942,20,NO,Good
274,YES,Married,112584,25,NO,Good
275,YES,Married,55591,0,YES,Good
276,NO,Single,44251,17,YES,Good
277,NO,Divorced,117364,11,NO,Good
278,NO,Married,114823,11,NO,Risky
279,YES,Single,74136,12,YES,Good
280,NO,Divorced,33184,1,NO,Risky
281,NO,Single,167403,7,YES,Good
282,YES,Married,59590,29,NO,Good
283,YES,Divorced,129276,22,NO,Good
284,NO,Divorced,188383,22,YES,Risky
285,NO,Single,63420,10,NO,Good
286,YES,Divorced,113724,6,NO,Good
287,YES,Single,77102,1,YES,Good
288,YES,Married,174196,21,YES,Risky
289,NO,Single,196816,14,NO,Good
290,YES,Married,193003,30,YES,Good
291,YES,Single,62475,26,YES,Good
292,YES,Single,76406,1,YES,Risky
293,NO,Divorced,43899,21,YES,Good
294,YES,Single,74074,2,NO,Good
295,YES,Married,40089,10,NO,Good
296,YES,Divorced,167600,26,NO,Good
297,NO,Married,36924,15,NO,Good
298,NO,Single,119904,21,YES,Good
299,YES,Single,197916,7,NO,Good
300,NO,Married,74052,30,NO,Good
301,YES,Married,39797,11,NO,Risky
302,YES,Divorced,97109,27,NO,Good
303,YES,Divorced,189061,13,YES,Good
304,YES,Divorced,106757,23,YES,Good
305,NO,Single,161265,29,YES,Good
306,YES,Divorced,185099,12,NO,Good
307,NO,Divorced,31819,25,NO,Good
308,YES,Married,183445,30,NO,Good
309,YES,Single,123761,20,YES,Good
310,YES,Divorced,189435,22,YES,Good
311,NO,Married,50013,19,NO,Good
312,YES,Single,31641,18,NO,Good
313,YES,Single,124848,2,NO,Good
314,NO,Single,85255,4,NO,Good
315,YES,Divorced,176278,19,NO,Risky
316,NO,Married,70323,25,NO,Good
317,YES,Married,116745,23,NO,Good
318,NO,Divorced,121324,14,YES,Good
319,YES,Divorced,153308,24,YES,Good
320,YES,Single,78897,11,YES,Good
321,NO,Single,84215,6,YES,Good
322,NO,Divorced,160932,24,YES,Good
323,YES,Married,165175,13,NO,Good
324,YES,Single,171288,15,NO,Good
325,NO,Single,25779,16,YES,Good
326,YES,Divorced,165001,19,YES,Risky
327,YES,Married,162777,7,NO,Risky
328,NO,Divorced,93414,12,YES,Good
329,NO,Single,39360,10,NO,Risky
330,NO,Married,43176,29,NO,Good
331,YES,Married,60999,15,YES,Risky
332,YES,Divorced,84132,1,NO,Good
333,YES,Single,44775,13,YES,Risky
334,NO,Single,118274,13,YES,Good
335,YES,Married,140998,15,NO,Good
336,NO,Married,73146,5,NO,Good
337,YES,Married,73490,7,NO,Risky
338,YES,Divorced,111264,23,NO,Risky
339,YES,Single,110940,10,NO,Risky
340,YES,Married,54437,21,YES,Good
341,NO,Married,83900,8,YES,Good
342,YES,Married,31097,7,YES,Good
343,YES,Divorced,161143,17,NO,Good
344,NO,Married,192313,5,YES,Good
345,YES,Divorced,118798,6,NO,Good
346,NO,Single,134635,30,YES,Risky
347,NO,Married,80991,0,YES,Risky
348,YES,Single,42269,2,NO,Good
349,YES,Divorced,72255,30,YES,Risky
350,NO,Married,89949,25,NO,Good
351,YES,Married,114922,12,NO,Good
352,NO,Divorced,72115,16,YES,Risky
353,YES,Married,141622,29,NO,Good
354,YES,Married,176891,27,YES,Risky
355,YES,Single,56488,17,NO,Good
356,NO,Married,46480,27,NO,Risky
357,NO,Married,84034,28,NO,Risky
358,YES,Single,96432,24,YES,Good
359,YES,Single,157299,11,NO,Good
360,YES,Single,107937,5,YES,Good
361,YES,Divorced,62671,20,NO,Good
362,YES,Divorced,75552,17,YES,Risky
363,YES,Single,52584,7,YES,Risky
364,YES,Married,62943,17,NO,Good
365,NO,Divorced,134321,10,YES,Good
366,YES,Married,131469,30,NO,Good
367,YES,Married,95404,24,YES,Risky
368,YES,Divorced,128428,14,NO,Good
369,NO,Married,89122,28,NO,Good
370,NO,Divorced,86119,5,YES,Good
371,YES,Single,75580,5,NO,Good
372,YES,Married,168473,9,NO,Good
373,NO,Married,175719,21,YES,Good
374,YES,Divorced,147614,9,YES,Good
375,NO,Married,130935,2,NO,Good
376,NO,Divorced,188067,26,NO,Good
377,YES,Single,103490,30,NO,Good
378,YES,Divorced,152471,6,NO,Good
379,NO,Single,112774,13,NO,Risky
380,YES,Married,197699,2,NO,Good
381,NO,Single,61920,4,NO,Good
382,YES,Divorced,139269,29,NO,Good
383,YES,Married,148246,5,YES,Good
384,YES,Married,147346,25,NO,Good
385,NO,Single,140132,27,NO,Good
386,NO,Single,140642,27,YES,Good
387,YES,Single,56597,9,YES,Good
388,YES,Divorced,151636,4,YES,Good
389,YES,Single,183187,5,YES,Good
390,YES,Single,57324,17,NO,Good
391,NO,Married,29934,1,NO,Good
392,YES,Divorced,37776,15,NO,Risky
393,NO,Married,68687,30,YES,Good
394,NO,Divorced,64990,21,YES,Good
395,YES,Single,183094,5,NO,Good
396,YES,Single,176330,21,NO,Good
397,NO,Married,91689,14,YES,Good
398,NO,Married,64070,2,YES,Risky
399,NO,Single,74497,21,NO,Good
400,YES,Married,197421,16,NO,Good
401,NO,Married,73065,20,NO,Good
402,YES,Divorced,105376,11,NO,Good
403,NO,Divorced,130912,27,YES,Good
404,YES,Divorced,34334,21,YES,Good
405,NO,Divorced,140266,28,NO,Good
406,NO,Married,107688,2,NO,Good
407,NO,Single,52144,6,NO,Good
408,YES,Divorced,77059,22,NO,Good
409,NO,Single,163058,1,NO,Good
410,NO,Divorced,41152,27,NO,Good
411,NO,Married,46253,19,NO,Good
412,YES,Single,28446,11,NO,Good
413,YES,Single,112890,11,YES,Good
414,NO,Divorced,27300,1,YES,Good
415,NO,Divorced,131493,21,NO,Good
416,NO,Single,33982,30,NO,Good
417,NO,Divorced,76625,2,NO,Good
418,YES,Divorced,104183,18,NO,Good
419,NO,Married,138074,20,NO,Good
420,NO,Divorced,84473,2,NO,Good
421,YES,Single,135185,13,NO,Good
422,NO,Divorced,191983,14,YES,Good
423,NO,Married,80249,19,YES,Good
424,YES,Married,94199,0,YES,Good
425,YES,Divorced,121506,27,NO,Good
426,YES,Divorced,50373,25,YES,Good
427,NO,Divorced,99025,10,NO,Good
428,YES,Married,128266,24,YES,Risky
429,NO,Single,153748,30,YES,Good
430,YES,Married,161215,8,NO,Good
431,NO,Single,168360,25,YES,Good
432,NO,Married,157217,11,YES,Good
433,NO,Married,129265,14,YES,Risky
434,YES,Single,87188,19,YES,Risky
435,NO,Divorced,111774,4,YES,Good
436,NO,Divorced,158057,4,YES,Good
437,YES,Married,117250,20,YES,Risky
438,NO,Single,74697,14,NO,Risky
439,YES,Divorced,48956,8,NO,Risky
440,NO,Single,170407,13,YES,Good
441,NO,Divorced,70314,24,NO,Good
442,YES,Single,193775,27,NO,Good
443,YES,Single,189209,9,NO,Risky
444,YES,Single,36956,14,NO,Risky
445,NO,Divorced,128451,12,NO,Good
446,NO,Single,65708,28,NO,Risky
447,NO,Married,166606,5,YES,Good
448,YES,Single,114597,28,YES,Good
449,NO,Married,27875,11,NO,Good
450,YES,Divorced,91936,8,YES,Good
451,YES,Divorced,108262,10,YES,Good
452,NO,Single,42620,10,NO,Good
453,YES,Single,41504,26,NO,Good
454,NO,Married,29602,15,YES,Good
455,NO,Married,65533,23,YES,Good
456,NO,Single,53788,23,YES,Good
457,NO,Married,36055,24,YES,Risky
458,YES,Single,110892,18,YES,Risky
459,YES,Divorced,125407,21,NO,Risky
460,NO,Divorced,54701,10,YES,Good
461,NO,Single,163901,6,YES,Good
462,NO,Divorced,149327,17,NO,Risky
463,NO,Divorced,40460,3,YES,Good
464,NO,Married,143349,16,YES,Good
465,NO,Divorced,116282,21,NO,Risky
466,NO,Married,186013,16,NO,Good
467,YES,Divorced,106946,20,YES,Good
468,YES,Divorced,38814,18,YES,Good
469,YES,Single,65487,13,YES,Good
470,YES,Married,148686,26,NO,Good
471,NO,Single,192410,21,YES,Risky
472,NO,Married,151963,11,YES,Good
473,YES,Single,147367,16,YES,Good
474,YES,Divorced,80729,0,NO,Good
475,NO,Single,36081,12,YES,Good
476,NO,Single,183057,7,YES,Good
477,YES,Divorced,158849,29,NO,Good
478,NO,Divorced,65242,6,NO,Good
479,YES,Married,68995,21,NO,Good
480,NO,Divorced,72252,26,YES,Good
481,YES,Single,120012,13,NO,Good
482,NO,Single,125771,12,NO,Good
483,NO,Single,100961,10,NO,Risky
484,YES,Married,114646,28,YES,Good
485,NO,Single,52766,23,NO,Good
486,YES,Single,57230,29,YES,Good
487,YES,Single,83402,13,YES,Good
488,YES,Single,76718,10,YES,Good
489,YES,Married,148821,6,NO,Good
490,NO,Married,120996,24,NO,Good
491,NO,Divorced,82029,10,NO,Risky
492,YES,Single,98123,18,YES,Good
493,NO,Married,103226,29,NO,Risky
494,NO,Single,197045,13,YES,Good
495,NO,Married,59156,24,NO,Good
496,YES,Divorced,59382,5,YES,Good
497,NO,Single,100331,3,NO,Good
498,YES,Single,164924,24,YES,Good
499,YES,Single,48744,2,YES,Good
500,YES,Single,158780,11,YES,Good
501,NO,Divorced,55842,4,YES,Good
502,NO,Married,53240,1,YES,Good
503,YES,Married,81550,17,YES,Good
504,NO,Divorced,198571,19,YES,Good
505,NO,Divorced,74910,15,YES,Good
506,NO,Single,111105,8,YES,Risky
507,YES,Single,101272,24,YES,Good
508,NO,Single,195357,19,NO,Good
509,NO,Married,65531,27,YES,Risky
510,YES,Married,75436,14,YES,Good
511,NO,Married,153233,5,YES,Good
512,YES,Single,137948,22,YES,Good
513,NO,Divorced,140400,10,NO,Good
514,NO,Divorced,31380,6,NO,Good
515,NO,Divorced,87868,13,NO,Good
516,YES,Single,76337,18,YES,Good
517,NO,Single,195078,26,NO,Risky
518,YES,Single,112591,26,YES,Good
519,YES,Single,162102,25,YES,Good
520,NO,Divorced,142426,8,YES,Good
521,NO,Divorced,51104,15,NO,Good
522,NO,Divorced,103343,10,NO,Good
523,NO,Divorced,42198,12,NO,Good
524,YES,Married,164391,27,NO,Risky
525,YES,Single,75307,23,NO,Good
526,NO,Divorced,82565,12,NO,Risky
527,NO,Married,180274,27,NO,Good
528,NO,Married,172612,10,NO,Good
529,NO,Divorced,83388,14,NO,Good
530,YES,Divorced,194421,17,YES,Good
531,YES,Married,124440,14,YES,Good
532,YES,Divorced,98662,16,NO,Good
533,NO,Divorced,54113,19,YES,Risky
534,YES,Married,91567,13,YES,Good
535,NO,Married,189851,3,NO,Good
536,NO,Single,157025,14,NO,Good
537,YES,Single,100651,6,NO,Good
538,NO,Married,119976,12,NO,Good
539,YES,Divorced,57390,8,NO,Good
540,YES,Single,110308,22,NO,Risky
541,YES,Divorced,191874,30,YES,Risky
542,YES,Married,199778,27,NO,Good
543,NO,Single,130816,13,NO,Good
544,NO,Single,133877,21,YES,Risky
545,YES,Divorced,109079,8,NO,Good
546,NO,Married,59091,6,NO,Good
547,YES,Single,42690,25,YES,Good
548,YES,Divorced,154393,9,YES,Good
549,NO,Married,74058,11,YES,Good
550,NO,Married,68160,2,YES,Good
551,YES,Married,123082,0,YES,Good
552,NO,Single,109191,5,YES,Good
553,NO,Single,26884,13,YES,Good
554,NO,Divorced,147788,27,NO,Good
555,NO,Single,53848,10,NO,Good
556,NO,Single,34242,12,NO,Good
557,YES,Married,157421,10,NO,Risky
558,NO,Divorced,191139,12,YES,Good
559,YES,Divorced,180424,26,NO,Good
560,NO,Divorced,182562,24,NO,Good
561,NO,Married,36861,29,YES,Good
562,YES,Divorced,100064,12,NO,Good
563,YES,Married,116495,6,YES,Good
564,YES,Married,30098,11,YES,Good
565,NO,Divorced,31064,28,NO,Good
566,NO,Married,33460,28,NO,Good
567,YES,Single,129912,30,NO,Risky
568,NO,Single,150036,22,YES,Good
569,YES,Single,38074,12,YES,Good
570,NO,Single,161629,29,YES,Good
571,NO,Single,95421,7,YES,Good
572,YES,Married,148068,13,NO,Good
573,YES,Married,116161,20,NO,Good
574,YES,Divorced,28768,29,YES,Good
575,NO,Divorced,95975,13,YES,Risky
576,YES,Married,79653,15,YES,Good
577,YES,Married,52940,5,YES,Good
578,NO,Divorced,185339,6,NO,Good
579,YES,Single,125112,7,YES,Good
580,YES,Divorced,123335,1,YES,Good
581,YES,Divorced,57473,10,YES,Good
582,YES,Married,32907,12,YES,Good
583,NO,Married,28874,19,NO,Good
584,NO,Divorced,155684,4,YES,Good
585,NO,Single,137622,2,YES,Good
586,YES,Single,106230,30,NO,Good
587,NO,Single,154677,26,YES,Good
588,YES,Married,93242,27,YES,Good
589,YES,Married,30774,10,NO,Good
590,NO,Married,85195,14,YES,Good
591,YES,Single,132859,18,YES,Risky
592,YES,Single,75143,16,NO,Good
593,NO,Divorced,131963,10,YES,Good
594,NO,Married,97526,9,YES,Good
595,YES,Divorced,39492,7,YES,Good
596,YES,Divorced,55369,2,YES,Good
597,NO,Divorced,154058,0,YES,Good

In [10]:
#Covert the categorical data into numbers 
fraudcheck[['Taxable_income','Marital_status','Undergrad','Urban']]=fraudcheck[['Taxable_income','Marital_status','Undergrad','Urban']].apply(lambda x: pd.factorize(x)[0])
fraudcheck[['Taxable_income','Marital_status','Undergrad','Urban']]

     Taxable_income  Marital_status  Undergrad  Urban
0                 0               0          0      0
1                 0               1          1      0
2                 0               2          0      0
3                 0               0          1      0
4                 0               2          0      1
5                 0               1          0      1
6                 0               1          0      0
7                 0               0          1      0
8                 0               0          0      0
9                 0               1          1      0
10                1               0          0      0
11                0               0          0      0
12                1               1          0      0
13                0               2          0      0
14                0               2          0      0
15                0               1          0      1
16                1               1          1      1
17                0               2          1      1
18                0               1          1      1
19                1               0          0      0
20                0               0          1      1
21                1               1          1      0
22                0               1          1      1
23                0               0          0      0
24                0               1          0      1
25                0               1          0      0
26                0               1          1      1
27                0               0          1      0
28                1               0          1      0
29                0               1          1      0
30                0               1          1      0
31                0               1          0      1
32                0               2          1      1
33                0               0          1      1
34                1               1          1      0
35                0               2          1      0
36                1               2          1      0
37                0               2          0      0
38                1               0          0      1
39                0               2          0      0
40                0               0          0      0
41                0               2          1      1
42                0               0          0      1
43                0               1          1      1
44                0               1          1      1
45                0               2          1      0
46                0               2          1      0
47                0               0          1      1
48                1               2          0      1
49                0               1          0      0
50                0               0          1      0
51                0               0          1      1
52                0               0          0      1
53                1               0          1      0
54                0               1          0      1
55                1               0          1      0
56                0               2          0      0
57                0               0          0      1
58                1               0          1      1
59                0               0          0      1
60                0               2          1      1
61                1               2          1      1
62                0               1          0      0
63                0               1          1      1
64                0               0          1      1
65                0               1          0      1
66                0               2          1      0
67                0               2          1      1
68                1               0          0      1
69                0               0          1      1
70                0               1          1      0
71                0               0          0      1
72                0               1          1      0
73                0               0          1      0
74                0               1          0      1
75                0               2          0      0
76                0               2          1      1
77                0               2          1      1
78                0               1          1      1
79                1               1          0      0
80                0               2          0      1
81                0               1          1      1
82                0               1          0      0
83                0               1          0      0
84                0               2          0      0
85                1               1          1      0
86                0               1          1      0
87                1               0          1      1
88                0               2          0      0
89                1               2          1      1
90                0               1          0      1
91                0               2          1      0
92                0               1          0      1
93                1               2          1      0
94                1               0          0      0
95                0               0          1      0
96                1               0          0      1
97                0               1          1      0
98                1               2          1      0
99                0               2          0      1
100               0               0          1      1
101               0               2          1      0
102               0               1          1      1
103               0               1          0      0
104               0               0          0      1
105               0               0          0      1
106               1               0          1      0
107               0               2          0      0
108               0               2          1      0
109               0               2          1      0
110               1               0          0      0
111               0               0          0      0
112               0               0          1      0
113               0               2          1      0
114               1               0          0      1
115               0               1          1      0
116               0               2          0      1
117               0               0          0      0
118               1               1          0      1
119               0               1          0      0
120               0               0          1      0
121               1               2          1      0
122               1               2          1      1
123               1               2          1      1
124               0               1          1      1
125               0               1          1      1
126               1               1          1      0
127               0               0          0      0
128               0               2          0      0
129               0               0          1      1
130               0               0          1      0
131               0               0          1      0
132               0               1          0      1
133               0               0          0      0
134               0               2          1      1
135               1               1          1      0
136               0               1          0      1
137               1               0          1      1
138               0               0          0      1
139               0               1          1      1
140               1               2          1      0
141               0               2          1      0
142               0               0          0      0
143               1               0          1      1
144               0               0          1      0
145               0               1          0      0
146               0               1          0      0
147               0               1          1      1
148               0               2          0      1
149               0               0          0      1
150               0               2          0      1
151               0               0          0      1
152               1               0          0      1
153               1               1          1      1
154               1               0          0      0
155               0               0          1      1
156               0               2          1      0
157               0               2          1      1
158               1               1          0      1
159               0               0          1      1
160               0               1          1      0
161               0               2          1      0
162               0               2          1      0
163               1               1          1      0
164               0               0          1      1
165               0               2          1      0
166               0               2          0      0
167               0               2          0      1
168               1               1          0      1
169               0               0          1      0
170               0               1          0      1
171               1               2          1      1
172               1               2          0      0
173               0               0          1      0
174               0               0          1      1
175               0               0          1      1
176               0               2          0      1
177               0               2          0      0
178               0               0          0      0
179               1               2          1      0
180               0               0          1      1
181               1               1          0      1
182               1               1          0      0
183               0               0          0      0
184               0               1          0      0
185               0               2          0      0
186               0               2          0      0
187               0               0          0      0
188               1               1          0      1
189               0               2          1      0
190               0               0          0      1
191               0               0          0      0
192               0               2          1      0
193               0               2          1      1
194               1               0          1      1
195               0               0          1      0
196               1               2          1      1
197               0               0          0      0
198               0               0          0      0
199               1               2          1      0
200               0               0          1      0
201               0               1          1      0
202               0               0          1      0
203               0               1          1      1
204               1               2          0      1
205               1               2          0      0
206               0               0          1      0
207               1               2          1      1
208               0               0          1      1
209               0               0          1      0
210               0               0          1      0
211               0               2          1      0
212               0               1          1      1
213               0               0          1      1
214               0               1          0      1
215               0               1          0      1
216               0               1          0      1
217               0               1          1      0
218               0               2          0      1
219               1               1          1      1
220               0               1          1      1
221               0               0          1      1
222               0               1          1      1
223               0               2          1      0
224               0               2          0      0
225               0               0          1      0
226               0               0          0      1
227               0               0          1      0
228               1               2          0      0
229               0               2          0      1
230               1               2          0      0
231               0               0          1      1
232               1               2          1      1
233              -1               2          0      0
234               0               0          0      1
235               0               1          0      1
236               0               2          1      1
237               1               2          0      0
238               0               0          1      0
239               0               1          0      1
240               0               0          0      0
241               1               0          1      0
242               0               1          0      0
243               0               1          0      0
244               0               0          1      1
245               0               0          0      1
246               0               0          1      1
247               1               1          1      1
248               1               0          0      0
249               0               0          1      0
250               0               2          0      1
251               0               0          1      1
252               0               0          0      0
253               0               0          1      1
254               0               1          0      1
255               0               2          1      1
256               0               2          1      1
257               0               2          1      0
258               0               1          0      0
259               1               2          0      1
260               0               0          1      1
261               0               0          0      0
262               0               1          0      1
263               0               2          1      0
264               0               0          0      1
265               1               2          0      0
266               0               2          1      0
267               1               0          0      1
268               0               0          0      0
269               0               2          1      0
270               0               2          0      1
271               0               0          0      1
272               0               0          0      0
273               0               1          1      1
274               0               2          1      1
275               0               2          1      0
276               0               0          0      0
277               0               1          0      1
278               1               2          0      1
279               0               0          1      0
280               1               1          0      1
281               0               0          0      0
282               0               2          1      1
283               0               1          1      1
284               1               1          0      0
285               0               0          0      1
286               0               1          1      1
287               0               0          1      0
288               1               2          1      0
289               0               0          0      1
290               0               2          1      0
291               0               0          1      0
292               1               0          1      0
293               0               1          0      0
294               0               0          1      1
295               0               2          1      1
296               0               1          1      1
297               0               2          0      1
298               0               0          0      0
299               0               0          1      1
300               0               2          0      1
301               1               2          1      1
302               0               1          1      1
303               0               1          1      0
304               0               1          1      0
305               0               0          0      0
306               0               1          1      1
307               0               1          0      1
308               0               2          1      1
309               0               0          1      0
310               0               1          1      0
311               0               2          0      1
312               0               0          1      1
313               0               0          1      1
314               0               0          0      1
315               1               1          1      1
316               0               2          0      1
317               0               2          1      1
318               0               1          0      0
319               0               1          1      0
320               0               0          1      0
321               0               0          0      0
322               0               1          0      0
323               0               2          1      1
324               0               0          1      1
325               0               0          0      0
326               1               1          1      0
327               1               2          1      1
328               0               1          0      0
329               1               0          0      1
330               0               2          0      1
331               1               2          1      0
332               0               1          1      1
333               1               0          1      0
334               0               0          0      0
335               0               2          1      1
336               0               2          0      1
337               1               2          1      1
338               1               1          1      1
339               1               0          1      1
340               0               2          1      0
341               0               2          0      0
342               0               2          1      0
343               0               1          1      1
344               0               2          0      0
345               0               1          1      1
346               1               0          0      0
347               1               2          0      0
348               0               0          1      1
349               1               1          1      0
350               0               2          0      1
351               0               2          1      1
352               1               1          0      0
353               0               2          1      1
354               1               2          1      0
355               0               0          1      1
356               1               2          0      1
357               1               2          0      1
358               0               0          1      0
359               0               0          1      1
360               0               0          1      0
361               0               1          1      1
362               1               1          1      0
363               1               0          1      0
364               0               2          1      1
365               0               1          0      0
366               0               2          1      1
367               1               2          1      0
368               0               1          1      1

In [11]:
x=fraudcheck.iloc[:,0:5]
y=fraudcheck['Taxable_income']

In [12]:
pd.set_option("display.max_rows", None) 
x

     Undergrad  Marital_status  City_population  Work_experience  Urban
0            0               0            50047               10      0
1            1               1           134075               18      0
2            0               2           160205               30      0
3            1               0           193264               15      0
4            0               2            27533               28      1
5            0               1           116382                0      1
6            0               1            80890                8      0
7            1               0           131253                3      0
8            0               0           102481               12      0
9            1               1           155482                4      0
10           0               0           102602               19      0
11           0               0            94875                6      0
12           0               1           148033               14      0
13           0               2            86649               16      0
14           0               2            57529               13      0
15           0               1           107764               29      1
16           1               1            34551               29      1
17           1               2            57194               25      1
18           1               1            59269                6      1
19           0               0           126953               30      0
20           1               0           147222               26      1
21           1               1            29106                7      0
22           1               1           155342               14      1
23           0               0            50495               12      0
24           0               1            28495               30      1
25           0               1           124606               27      0
26           1               1           169128               15      1
27           1               0            28542               12      0
28           1               0           128766                5      0
29           1               1            41863               30      0
30           1               1           117788                0      0
31           0               1           147414               21      1
32           1               2            51911               23      1
33           1               0           157251               21      1
34           1               1           183767                1      0
35           1               2            41117               30      0
36           1               2           193995                5      0
37           0               2            66912                5      0
38           0               0           177575                3      1
39           0               2            54981               16      0
40           0               0           199697               26      0
41           1               2            91524                1      1
42           0               0            51666               12      1
43           1               1            50020               10      1
44           1               1            98880               22      1
45           1               2           183095               14      0
46           1               2           137346               27      0
47           1               0            34964                2      1
48           0               2            35480               12      1
49           0               1           160195               15      0
50           1               0           145804                3      0
51           1               0           174042               30      1
52           0               0            91828               23      1
53           1               0           139143                7      0
54           0               1            98207               23      1
55           1               0            89965               16      0
56           0               2            69832               25      0
57           0               0            70744               13      1
58           1               0           158047               15      1
59           0               0           102228               11      1
60           1               2            91138               23      1
61           1               2            86169                8      1
62           0               1           147684               13      0
63           1               1            95831                9      1
64           1               0           118261               15      1
65           0               1           194738               29      1
66           1               2            66985               12      0
67           1               2           173986               24      1
68           0               0           139642                5      1
69           1               0            86896               29      1
70           1               1            80904                3      0
71           0               0           105680               22      1
72           1               1           108300               27      0
73           1               0           174789                2      0
74           0               1           182319               17      1
75           0               2            50404               19      0
76           1               2           129164               11      1
77           1               2           118344               26      1
78           1               1           143153                0      1
79           0               1           140885                7      0
80           0               2            28184               26      1
81           1               1           121608               24      1
82           0               1           111068               26      0
83           0               1            73963               18      0
84           0               2           178083                4      0
85           1               1           125155               12      0
86           1               1            97520               29      0
87           1               0            64075               23      1
88           0               2            63896               24      0
89           1               2           176050               20      1
90           0               1           101232               29      1
91           1               2            73733               10      0
92           0               1           114621               13      1
93           1               2           137676                3      0
94           0               0           122705                6      0
95           1               0           121498               28      0
96           0               0            63622               17      1
97           1               1            37849               19      0
98           1               2            77053               18      0
99           0               2           114350               12      1
100          1               0            46444               25      1
101          1               2            50490               20      0
102          1               1            91488               23      1
103          0               1            76318                5      0
104          0               0           174423               14      1
105          0               0            46893               15      1
106          1               0            58535               20      0
107          0               2            52424                6      0
108          1               2           120894               10      0
109          1               2           178585                8      0
110          0               0            32450               19      0
111          0               0           164526               11      0
112          1               0           193038               26      0
113          1               2           100347                7      0
114          0               0           197934                7      1
115          1               1            78251               21      0
116          0               2           132570               12      1
117          0               0            96370               29      0
118          0               1           199174               10      1
119          0               1            47202               30      0
120          1               0           135886               11      0
121          1               2            86648               16      0
122          1               2           140762               26      1
123          1               2            79683               26      1
124          1               1           139324               13      1
125          1               1           155669               11      1
126          1               1           195022                3      0
127          0               0            93035               28      0
128          0               2           100897               27      0
129          1               0            65469               26      1
130          1               0            87730                7      0
131          1               0           174321               16      0
132          0               1            67820               12      1
133          0               0            86646               14      0
134          1               2           190365               28      1
135          1               1            75323               19      0
136          0               1            53513                9      1
137          1               0           115884                6      1
138          0               0           155335               25      1
139          1               1            86904               20      1
140          1               2            93390                4      0
141          1               2           194364               23      0
142          0               0           122654               26      0
143          1               0           154013               11      1
144          1               0           156503               29      0
145          0               1           197422                2      0
146          0               1            57931               28      0
147          1               1           163252               28      1
148          0               2           197038               21      1
149          0               0            49505               25      1
150          0               2           161759               28      1
151          0               0           109110               10      1
152          0               0            91889               16      1
153          1               1           114841               28      1
154          0               0            82520               29      0
155          1               0           139624                7      1
156          1               2           125987                3      0
157          1               2           115631                5      1
158          0               1           163347               11      1
159          1               0            28504                1      1
160          1               1            79972                0      0
161          1               2           185596               30      0
162          1               2           177468               21      0
163          1               1            91851               15      0
164          1               0           153192               28      1
165          1               2            38463               23      0
166          0               2            73466               22      0
167          0               2           194381               25      1
168          0               1           167629               30      1
169          1               0            76933                6      0
170          0               1           143402               10      1
171          1               2           103614               24      1
172          0               2            52819               23      0
173          1               0           105110               16      0
174          1               0           149857                8      1
175          1               0            57055               13      1
176          0               2            75169               28      1
177          0               2            31156               13      0
178          0               0            85832               15      0
179          1               2           192451               22      0
180          1               0           149101               19      1
181          0               1            36116               20      1
182          0               1            89632                4      0
183          0               0            39523               30      0
184          0               1            70138               15      0
185          0               2            92975                0      0
186          0               2           166976               19      0
187          0               0            59558                5      0
188          0               1           137569               10      1
189          1               2           189301               11      0
190          0               0            90459               19      1
191          0               0           176341                7      0
192          1               2           126556               10      0
193          1               2           198213               25      1
194          1               0           103981               28      1
195          1               0           181370               13      0
196          1               2            28410               21      1
197          0               0            98056                4      0
198          0               0            48025               28      0
199          1               2           145744                9      0
200          1               0           162777               17      0
201          1               1            58225               27      0
202          1               0            28661                0      0
203          1               1           117260                4      1
204          0               2           173091               14      1
205          0               2           131906               20      0
206          1               0            52227               16      0
207          1               2           138108               28      1
208          1               0           141502                3      1
209          1               0           186239               25      0
210          1               0           125993               13      0
211          1               2            57194                8      0
212          1               1           112659               14      1
213          1               0           107069               13      1
214          0               1           140159               16      1
215          0               1            28576               22      1
216          0               1            85128               22      1
217          1               1           179220               19      0
218          0               2            38091               19      1
219          1               1            26814                9      1
220          1               1           115168               30      1
221          1               0           134135               14      1
222          1               1           168248               27      1
223          1               2           192297               17      0
224          0               2            55717               25      0
225          1               0           125883                0      0
226          0               0            77719               28      1
227          1               0           182921               17      0
228          0               2           100696                9      0
229          0               2            35780               10      1
230          0               2            81593               14      0
231          1               0           153147                2      1
232          1               2           150349                2      1
233          0               2            63701               19      0
234          0               0           102498               14      1
235          0               1            87541                9      1
236          1               2           193193                3      1
237          0               2           128996                3      0
238          1               0            72968                9      0
239          0               1            76145               26      1
240          0               0           139146               30      0
241          1               0            31377               18      0
242          0               1            84368                2      0
243          0               1           181549               10      0
244          1               0           154647               27      1
245          0               0           183221               24      1
246          1               0            38139               25      1
247          1               1           108245                1      1
248          0               0           105374               17      0
249          1               0            35376                0      0
250          0               2           156973               16      1
251          1               0           173228                7      1
252          0               0            40855               28      0
253          1               0            77256               29      1
254          0               1           193263               26      1
255          1               2           170030                8      1
256          1               2           168568               14      1
257          1               2            31611               17      0
258          0               1            74119               28      0
259          0               2           197841                7      1
260          1               0            92333               28      1
261          0               0            68788                7      0
262          0               1           120415               21      1
263          1               2            69386               21      0
264          0               0           118899                5      1
265          0               2           101996                4      0
266          1               2           173276               17      0
267          0               0           183946               11      1
268          0               0            98378                3      0
269          1               2           125450               13      0
270          0               2           130680                5      1
271          0               0           183682               20      1
272          0               0           126488                1      0
273          1               1            58942               20      1
274          1               2           112584               25      1
275          1               2            55591                0      0

In [13]:
y

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     0
12     1
13     0
14     0
15     0
16     1
17     0
18     0
19     1
20     0
21     1
22     0
23     0
24     0
25     0
26     0
27     0
28     1
29     0
30     0
31     0
32     0
33     0
34     1
35     0
36     1
37     0
38     1
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     1
49     0
50     0
51     0
52     0
53     1
54     0
55     1
56     0
57     0
58     1
59     0
60     0
61     1
62     0
63     0
64     0
65     0
66     0
67     0
68     1
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     0
78     0
79     1
80     0
81     0
82     0
83     0
84     0
85     1
86     0
87     1
88     0
89     1
90     0
91     0
92     0
93     1
94     1
95     0
96     1
97     0
98     1
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    1
107    0
108    0
109    0
110    1
111    0
112    0
113    0
114    1
115    0
116    0
117    0
118    1
119    0
120    0
121    1
122    1
123    1
124    0
125    0
126    1
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    1
136    0
137    1
138    0
139    0
140    1
141    0
142    0
143    1
144    0
145    0
146    0
147    0
148    0
149    0
150    0
151    0
152    1
153    1
154    1
155    0
156    0
157    0
158    1
159    0
160    0
161    0
162    0
163    1
164    0
165    0
166    0
167    0
168    1
169    0
170    0
171    1
172    1
173    0
174    0
175    0
176    0
177    0
178    0
179    1
180    0
181    1
182    1
183    0
184    0
185    0
186    0
187    0
188    1
189    0
190    0
191    0
192    0
193    0
194    1
195    0
196    1
197    0
198    0
199    1
200    0
201    0
202    0
203    0
204    1
205    1
206    0
207    1
208    0
209    0
210    0
211    0
212    0
213    0
214    0
215    0
216    0
217    0
218    0
219    1
220    0
221    0
222    0
223    0
224    0
225    0
226    0
227    0
228    1
229    0
230    1
231    0
232    1
233   -1
234    0
235    0
236    0
237    1
238    0
239    0
240    0
241    1
242    0
243    0
244    0
245    0
246    0
247    1
248    1
249    0
250    0
251    0
252    0
253    0
254    0
255    0
256    0
257    0
258    0
259    1
260    0
261    0
262    0
263    0
264    0
265    1
266    0
267    1
268    0
269    0
270    0
271    0
272    0
273    0
274    0
275    0
276    0
277    0
278    1
279    0
280    1
281    0
282    0
283    0
284    1
285    0
286    0
287    0
288    1
289    0
290    0
291    0
292    1
293    0
294    0
295    0
296    0
297    0
298    0
299    0
300    0
301    1
302    0
303    0
304    0
305    0
306    0
307    0
308    0
309    0
310    0
311    0
312    0
313    0
314    0
315    1
316    0
317    0
318    0
319    0
320    0
321    0
322    0
323    0
324    0
325    0
326    1
327    1
328    0
329    1
330    0
331    1
332    0
333    1
334    0
335    0
336    0
337    1
338    1
339    1
340    0
341    0
342    0
343    0
344    0
345    0
346    1
347    1
348    0
349    1
350    0
351    0
352    1
353    0
354    1
355    0
356    1
357    1
358    0
359    0
360    0
361    0
362    1
363    1
364    0
365    0
366    0
367    1
368    0
369    0
370    0
371    0
372    0
373    0
374    0
375    0
376    0
377    0
378    0
379    1
380    0
381    0
382    0
383    0
384    0
385    0
386    0
387    0
388    0
389    0
390    0
391    0
392    1
393    0
394    0
395    0
396    0
397    0
398    1
399    0
400    0
401    0
402    0
403    0
404    0
405    0
406    0
407    0
408    0
409    0
410    0
411    0
412    0
413    0
414    0
415    0
416    0
417    0
418    0
419    0
420    0
421    0
422    0
423    0
424    0
425    0
426    0
427    0
428    1
429    0
430    0
431    0
432    0
433    1
434    1
435    0
436    0
437    1
438    1
439    1
440    0
441    0
442    0
443    1
444    1
445    0
446    1
447    0
448    0
449    0
450    0
451    0
452    0
453    0
454    0
455    0
456    0
457    1
458    1
459    1
460    0
461    0
462    1
463    0
464    0
465    1
466    0
467    0
468    0
469    0
470    0
471    1
472    0
473    0
474    0
475    0
476    0
477    0
478    0
479    0
480    0
481    0
482    0
483    1
484    0
485    0
486    0
487    0
488    0
489    0
490    0
491    1
492    0
493    1
494    0
495    0
496    0
497    0
498    0
499    0
500    0
501    0
502    0
503    0
504    0
505    0
506    1
507    0
508    0
509    1
510    0
511    0
512    0
513    0
514    0
515    0
516    0
517    1
518    0
519    0
520    0
521    0
522    0
523    0
524    1
525    0
526    1
527    0
528    0
529    0
530    0
531    0
532    0
533    1
534    0
535    0
536    0
537    0
538    0
539    0
540    1
541    1
542    0
543    0
544    1
545    0
546    0
547    0
548    0
549    0
550    0
551    0
552    0
553    0
554    0
555    0
556    0
557    1
558    0
559    0
560    0
561    0
562    0
563    0
564    0
565    0
566    0
567    1
568    0
569    0
570    0
571    0
572    0
573    0
574    0
575    1
576    0
577    0
578    0
579    0
580    0
581    0
582    0
583    0
584    0
585    0
586    0
587    0
588    0
589    0
590    0
591    1
592    0
593    0
594    0
595    0
596    0
597    0
598    0
599    0
Name: Taxable_income, dtype: int64

In [14]:
# Random Forest Classification
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
X = x
Y = y
num_trees = 150
max_features = 3
kfold = KFold(n_splits=10, random_state=7, shuffle= True)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
results = cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.7416666666666666